// Generated by scripts/build-card-script-index.ts. Do not edit by hand.
import s_bilbos_deadly_slice from "./bilbos_deadly_slice.json";
import s_cancel from "./cancel.json";
import s_dragon_fodder from "./dragon_fodder.json";
import s_fell from "./fell.json";
import s_flame_lash from "./flame_lash.json";
import s_giant_growth from "./giant_growth.json";
import s_hop_to_it from "./hop_to_it.json";
import s_lightning_strike from "./lightning_strike.json";
import s_wander_off from "./wander_off.json";

export const RAW_CARD_SCRIPTS: unknown[] = [
  s_bilbos_deadly_slice,
  s_cancel,
  s_dragon_fodder,
  s_fell,
  s_flame_lash,
  s_giant_growth,
  s_hop_to_it,
  s_lightning_strike,
  s_wander_off,
];
