/**
 * Unit tests for the Tauri Content Security Policy (issue #1273).
 *
 * Asserts the contract documented in CONTRIBUTING.md § "Security model":
 *
 *   1. `src-tauri/tauri.conf.json` ships with a non-null `app.security.csp`
 *      string.
 *   2. That string is **byte-identical** to the canonical CSP exported by
 *      `src/lib/security/csp-allowlist.ts` (the single source of truth).
 *   3. The CSP does **not** contain `unsafe-eval`, a bare `*` source, or
 *      a bare `data:` source outside the directives that legitimately
 *      need it (`img-src`, `font-src`).
 *   4. Every hostname from `REMOTE_IMAGE_HOSTS` and `REMOTE_FONT_HOSTS`
 *      appears in the corresponding CSP directive.
 *   5. `connect-src` explicitly enumerates every host in
 *      `REMOTE_CONNECT_HOSTS` and contains NO bare `https:` or `wss:`
 *      scheme-wide wildcard (issue #1584).
 *   6. The Next.js image optimizer (`next.config.ts`) agrees with the
 *      CSP `img-src` directive.
 *   7. The WEB deployment CSP (issue #1822) emitted by
 *      `next.config.ts` `headers()` mirrors `TAURI_CSP` directive-for-
 *      directive with one documented exception (`script-src`), and is
 *      derived from the same allowlists — the #1273 sync extended to
 *      three consumers.
 *   8. The non-CSP security headers (`X-Content-Type-Options`,
 *      `Referrer-Policy`, `Strict-Transport-Security`) are configured
 *      in `next.config.ts` for every route.
 *
 * These tests run in plain Node (no Tauri runtime required) so they fail
 * fast in CI without spinning up a webview.
 */

import * as fs from "fs";
import * as path from "path";

import {
  TAURI_CSP,
  buildTauriCsp,
  WEB_CSP,
  REMOTE_IMAGE_HOSTS,
  REMOTE_FONT_HOSTS,
  REMOTE_CONNECT_HOSTS,
} from "../src/lib/security/csp-allowlist";

const REPO_ROOT = path.resolve(__dirname, "..");
const TAURI_CONF = path.join(REPO_ROOT, "src-tauri", "tauri.conf.json");
const NEXT_CONFIG = path.join(REPO_ROOT, "next.config.ts");

function readText(file: string): string {
  return fs.readFileSync(file, "utf8");
}

type TauriConf = {
  app: {
    security: {
      csp: string | null;
      [key: string]: unknown;
    };
    [key: string]: unknown;
  };
  [key: string]: unknown;
};

function loadTauriConf(): TauriConf {
  return JSON.parse(readText(TAURI_CONF)) as TauriConf;
}

/** Split a CSP into its directive parts (`name value1 value2...`). */
function splitDirectives(csp: string): Map<string, string[]> {
  const out = new Map<string, string[]>();
  for (const raw of csp.split(";")) {
    const trimmed = raw.trim();
    if (!trimmed) continue;
    const [name, ...rest] = trimmed.split(/\s+/);
    out.set(name.toLowerCase(), rest);
  }
  return out;
}

/** Extract every host token from a single CSP directive's value list. */
function hostsInDirective(values: readonly string[]): string[] {
  const out: string[] = [];
  for (const v of values) {
    // Strip scheme prefix, leave host[:port][/path]
    const m = /^(?:[a-z]+:)?\/\/([^/]+)/.exec(v);
    if (m) out.push(m[1]);
    else if (/^[a-z0-9.*-]+\.[a-z0-9-]/i.test(v)) out.push(v);
  }
  return out;
}

describe("Tauri CSP audit (issue #1273)", () => {
  const conf = loadTauriConf();
  const cspValue = conf.app.security.csp as string;

  test("tauri.conf.json has a non-null CSP", () => {
    expect(cspValue).not.toBeNull();
    expect(typeof cspValue).toBe("string");
    expect((cspValue ?? "").length).toBeGreaterThan(0);
  });

  test("CSP is generated by buildTauriCsp (single source of truth, issue #1918)", () => {
    // Extract the nonce from the config CSP (written by prebuild:tauri).
    const nonceMatch = /'nonce-([A-Za-z0-9+/=_-]+)'/.exec(cspValue);
    const nonce = nonceMatch ? nonceMatch[1] : undefined;
    // buildTauriCsp must produce the exact same string.
    expect(cspValue).toBe(buildTauriCsp(nonce));
  });

  test("CSP does not enable unsafe-eval or wildcard sources", () => {
    expect(cspValue).not.toMatch(/'unsafe-eval'(?![-a-z])/i);
    // 'unsafe-inline' is allowed ONLY in style-src (documented trade-off).
    expect(cspValue).not.toMatch(/\s\*\s/); // bare wildcard token
    expect(cspValue).not.toMatch(/^[^;]*\bfont-src[^;]*\*\b/m);
    expect(cspValue).not.toMatch(/^[^;]*\bconnect-src[^;]*\*:/m);
  });

  test("img-src allows every host in REMOTE_IMAGE_HOSTS", () => {
    const directives = splitDirectives(cspValue);
    const imgValues = directives.get("img-src") ?? [];
    const hosts = hostsInDirective(imgValues);
    for (const host of REMOTE_IMAGE_HOSTS) {
      expect(hosts).toContain(host.hostname);
    }
  });

  test("font-src allows every host in REMOTE_FONT_HOSTS", () => {
    const directives = splitDirectives(cspValue);
    const fontValues = directives.get("font-src") ?? [];
    const hosts = hostsInDirective(fontValues);
    for (const host of REMOTE_FONT_HOSTS) {
      expect(hosts).toContain(host.hostname);
    }
  });

  test("connect-src contains NO bare scheme wildcard (issue #1584)", () => {
    const directives = splitDirectives(cspValue);
    const connectValues = directives.get("connect-src") ?? [];
    const joined = connectValues.join(" ");
    // Bare `https:` and `wss:` tokens defeat the purpose of the CSP — an
    // attacker with a script injection could otherwise exfiltrate data to
    // any HTTPS endpoint, or open a WebSocket to any WSS endpoint. The
    // directives must enumerate hosts explicitly; no WSS pattern remains
    // (the PeerJS broker wildcard was removed with the orphaned dep).
    expect(connectValues).not.toContain("https:");
    expect(connectValues).not.toContain("wss:");
    // Defence in depth: a bare scheme token might appear mid-string with
    // surrounding whitespace; reject it wherever it shows up.
    expect(joined).not.toMatch(/(?:^|\s)https:(?:\s|$)/);
    expect(joined).not.toMatch(/(?:^|\s)wss:(?:\s|$)/);
    // Sanity check: 'self' must still be allowed (offline / same-origin).
    expect(connectValues).toContain("'self'");
  });

  test("connect-src explicitly enumerates every REMOTE_CONNECT_HOSTS host (issue #1584)", () => {
    const directives = splitDirectives(cspValue);
    const connectValues = directives.get("connect-src") ?? [];
    // Every HTTPS host in the allow-list must appear literally as
    // `https://hostname` — no scheme-wide fallback to satisfy the
    // coverage check. If a future AI provider is added to
    // PROVIDER_ENV_MAPPING it MUST also be added to REMOTE_CONNECT_HOSTS
    // so this test passes.
    for (const host of REMOTE_CONNECT_HOSTS) {
      expect(connectValues).toContain(`https://${host.hostname}`);
    }
  });

  test("connect-src has no stray scheme source beyond the documented set (issue #1584)", () => {
    // Defence in depth: enumerate the full allow-list as a JSON-style
    // assertion so a future contributor adding a new provider cannot
    // silently bypass the per-host checks above.
    const directives = splitDirectives(cspValue);
    const connectValues = directives.get("connect-src") ?? [];
    const expected = new Set<string>([
      "'self'",
      // Loopback WebSocket sources: Next.js dev-mode HMR + the local
      // signaling WS. CSP 'self' does not cover ws://, so they are
      // enumerated explicitly (loopback only, no ws/wss wildcard — #1584).
      // Surfaced by the e2e multiplayer timeouts after #1822.
      "ws://localhost:*",
      "ws://127.0.0.1:*",
      ...REMOTE_CONNECT_HOSTS.map((host) => `https://${host.hostname}`),
    ]);
    // Sort-compare so the assertion message lists every unexpected /
    // missing token.
    expect([...connectValues].sort()).toEqual([...expected].sort());
  });

  test("script-src forbids 'unsafe-inline' (only 'unsafe-eval' via wasm is allowed)", () => {
    const directives = splitDirectives(cspValue);
    const scriptValues = directives.get("script-src") ?? [];
    expect(scriptValues.join(" ")).not.toMatch(/'unsafe-inline'/);
    // WASM-unsafe-eval is OK; raw unsafe-eval is not.
    expect(scriptValues.join(" ")).not.toMatch(/'unsafe-eval'(?![-a-z])/i);
  });

  test("frame-ancestors, object-src, frame-src are restrictive", () => {
    const directives = splitDirectives(cspValue);
    expect(directives.get("frame-ancestors")).toEqual(["'none'"]);
    expect(directives.get("object-src")).toEqual(["'none'"]);
    expect(directives.get("frame-src")).toEqual(["'none'"]);
  });

  test("base-uri and form-action are pinned to 'self'", () => {
    const directives = splitDirectives(cspValue);
    expect(directives.get("base-uri")).toEqual(["'self'"]);
    expect(directives.get("form-action")).toEqual(["'self'"]);
  });
});

describe("next.config.ts agrees with the CSP img-src (issue #1273)", () => {
  test("remotePatterns is derived from the shared csp-allowlist (no drift)", () => {
    const text = readText(NEXT_CONFIG);
    // The point of the allow-list is single-source-of-truth. We can't
    // ast-parse here, but we can verify both:
    //   (a) the file imports REMOTE_IMAGE_HOSTS from csp-allowlist, and
    //   (b) the remotePatterns config is built from that import via .map
    // If either is true, the literal hostname strings will never appear
    // in next.config.ts — by design.
    expect(text).toMatch(
      /from\s+["']\.\.?\/src\/lib\/security\/csp-allowlist["']/,
    );
    expect(text).toMatch(/remotePatterns\s*:\s*REMOTE_IMAGE_HOSTS\.map/);
  });
});

describe("web deployment security headers (issue #1822)", () => {
  test("next.config.ts emits the allowlist-derived CSP on every route", () => {
    const text = readText(NEXT_CONFIG);
    // Same text-based pattern as the remotePatterns test above: the CSP
    // value must be the shared WEB_CSP export, not a copied host list.
    expect(text).toMatch(
      /from\s+["']\.\.?\/src\/lib\/security\/csp-allowlist["']/,
    );
    expect(text).toMatch(
      /key:\s*["']Content-Security-Policy["'],\s*value:\s*WEB_CSP/,
    );
    // Applied broadly: a source pattern covering all routes.
    expect(text).toMatch(/source:\s*["']\/\(\.\*\)["']/);
  });

  test("non-CSP security headers are configured", () => {
    const text = readText(NEXT_CONFIG);
    expect(text).toMatch(
      /key:\s*["']X-Content-Type-Options["'],\s*value:\s*["']nosniff["']/,
    );
    expect(text).toMatch(
      /key:\s*["']Referrer-Policy["'],\s*value:\s*["']strict-origin-when-cross-origin["']/,
    );
    // HSTS: present with a numeric max-age (value documented in config).
    expect(text).toMatch(
      /key:\s*["']Strict-Transport-Security["'],\s*value:\s*["']max-age=\d+["']/,
    );
  });

  test("WEB_CSP mirrors TAURI_CSP directive-for-directive except script-src", () => {
    // The core #1273 sync invariant, extended to the third consumer:
    // the web policy must be the desktop policy (same directives, same
    // values, same order of hosts) with only the documented script-src
    // delta. Any host added to the allowlists shows up in both; any
    // hand-edit to either string fails here.
    const tauri = splitDirectives(TAURI_CSP);
    const web = splitDirectives(WEB_CSP);
    expect([...web.keys()].sort()).toEqual([...tauri.keys()].sort());
    for (const [name, values] of tauri) {
      if (name === "script-src") continue;
      expect(web.get(name)).toEqual(values);
    }
  });

  test("WEB_CSP script-src documents the web-only inline requirement", () => {
    const web = splitDirectives(WEB_CSP);
    const script = web.get("script-src") ?? [];
    // 'unsafe-inline' is required on the web deployment: Next.js App
    // Router streams its flight payload as inline <script> tags and —
    // unlike the Tauri webview, which auto-injects nonces into inline
    // scripts — no runtime layer can mint per-request nonces from
    // next.config headers(). Everything else stays as strict as the
    // desktop.
    expect(script).toContain("'self'");
    expect(script).toContain("'wasm-unsafe-eval'");
    expect(script).toContain("'unsafe-inline'");
    // Plain 'unsafe-eval' stays forbidden in the shipped policy (Jest
    // runs with NODE_ENV=test, i.e. the non-development branch).
    expect(script.join(" ")).not.toMatch(/'unsafe-eval'(?![-a-z])/i);
  });

  test("WEB_CSP enumerates the shared allowlists (img/font/connect)", () => {
    const web = splitDirectives(WEB_CSP);
    const imgHosts = hostsInDirective(web.get("img-src") ?? []);
    for (const host of REMOTE_IMAGE_HOSTS) {
      expect(imgHosts).toContain(host.hostname);
    }
    const fontHosts = hostsInDirective(web.get("font-src") ?? []);
    for (const host of REMOTE_FONT_HOSTS) {
      expect(fontHosts).toContain(host.hostname);
    }
    const connect = web.get("connect-src") ?? [];
    for (const host of REMOTE_CONNECT_HOSTS) {
      expect(connect).toContain(`https://${host.hostname}`);
    }
    // No scheme-wide exfiltration wildcards on the web either (#1584).
    expect(connect).not.toContain("https:");
    expect(connect).not.toContain("wss:");
    expect(connect).toContain("'self'");
  });

  test("clickjacking: frame-ancestors 'none' in CSP, no redundant X-Frame-Options", () => {
    // Deliberate choice (documented in next.config.ts): the CSP
    // frame-ancestors directive supersedes X-Frame-Options in every
    // CSP-capable browser, so the legacy header is intentionally absent.
    const web = splitDirectives(WEB_CSP);
    expect(web.get("frame-ancestors")).toEqual(["'none'"]);
    // Not emitted as a header (prose may still mention the choice).
    expect(readText(NEXT_CONFIG)).not.toMatch(/key:\s*["']X-Frame-Options["']/);
  });
});
