/**
 * Smoke tests for the Tauri 2 updater plumbing (issue #1403).
 *
 * Asserts the contracts documented in the issue acceptance criteria that
 * can be checked without spinning up a Tauri runtime:
 *
 *   1. `tauri.conf.json` `plugins.updater.pubkey` is a non-empty
 *      base64-encoded minisign public key.
 *   2. `tauri.conf.json` `plugins.updater.endpoints` contains at least
 *      one HTTPS URL pointing to a `latest.json`-shaped path.
 *   3. `src-tauri/capabilities/default.json` includes `updater:default`.
 *   4. The pubkey in (1) is byte-identical to the public-key file
 *      generated by `tauri signer generate` (the .pub counterpart of the
 *      private key consumed by GitHub Actions at build time). This is the
 *      check that prevents a key-rotation drift between the bundle and
 *      the locally-stored .pub file.
 *   5. `bundle.createUpdaterArtifacts` is enabled so `tauri build`
 *      actually emits the `.sig` files the manifest needs.
 *
 * These tests run in plain Node (no Tauri runtime required) so they fail
 * fast in CI without spinning up a webview — same convention as the
 * existing capability-audit / csp-audit suites.
 */

import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const REPO_ROOT = path.resolve(__dirname, "..");
const TAURI_CONF = path.join(REPO_ROOT, "src-tauri", "tauri.conf.json");
const CAPABILITIES_DEFAULT = path.join(
  REPO_ROOT,
  "src-tauri",
  "capabilities",
  "default.json",
);

function readJson(file: string): Record<string, unknown> {
  return JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, unknown>;
}

describe("Tauri 2 updater wiring (issue #1403)", () => {
  const conf = readJson(TAURI_CONF) as {
    bundle?: { createUpdaterArtifacts?: boolean };
    plugins?: {
      updater?: { active?: boolean; pubkey?: string; endpoints?: string[] };
    };
  };
  const cap = readJson(CAPABILITIES_DEFAULT) as {
    permissions: string[];
  };
  const updater = conf.plugins?.updater ?? {};
  const pubkey = typeof updater.pubkey === "string" ? updater.pubkey : "";
  const endpoints = Array.isArray(updater.endpoints) ? updater.endpoints : [];

  test("updater plugin is active in tauri.conf.json", () => {
    expect(updater.active).toBe(true);
  });

  test("updater.pubkey is a non-empty minisign-format base64 string", () => {
    expect(pubkey.length).toBeGreaterThan(0);
    // Minisign public keys begin with `untrusted comment:` followed by
    // a base64 line containing the key id + key bytes. Tauri accepts
    // both single-line and two-line serializations; we tolerate both.
    expect(pubkey).toMatch(
      /^dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6/,
    );
    // The actual key material — either on a second line (minisign
    // canonical form) or concatenated onto the same line (the
    // JSON-embedded form). Either way it must be at least 42 chars
    // (a raw ed25519 key is 32 bytes = 44 base64 chars before padding).
    const lines = pubkey.split(/\r?\n/).filter((l) => l.length > 0);
    if (lines.length >= 2) {
      expect(lines[1].length).toBeGreaterThanOrEqual(42);
    } else {
      const tail = lines[0].slice(76).replace(/[^A-Za-z0-9+/=]/g, "");
      expect(tail.length).toBeGreaterThanOrEqual(42);
    }
  });

  test("updater.endpoints contains at least one HTTPS URL with latest.json", () => {
    expect(endpoints.length).toBeGreaterThan(0);
    for (const url of endpoints) {
      expect(url).toMatch(/^https:\/\//);
      // The default GitHub Releases static-JSON endpoint.
      expect(url).toMatch(/latest\.json$/);
    }
  });

  test("capabilities/default.json grants updater:default", () => {
    expect(cap.permissions).toContain("updater:default");
  });

  test("bundle.createUpdaterArtifacts is enabled so .sig files are emitted", () => {
    // Without this, `tauri build` does not produce the per-installer
    // signatures the updater manifest references, and the in-app check
    // will reject every release.
    expect(conf.bundle?.createUpdaterArtifacts).toBe(true);
  });

  test("updater.pubkey matches the on-disk .pub file (no key-rotation drift)", () => {
    // Search a small set of canonical Tauri key locations. The CI
    // environment provides TAURI_SIGNING_PRIVATE_KEY_PATH; on a
    // developer machine the key lives at ~/.tauri/<name>.key.pub. We
    // don't enforce that *a* key exists (this test only fails the
    // match check) — a missing key is a separate operator concern.
    const home = os.homedir();
    const candidates = [
      path.join(home, ".tauri", "planar-nexus.key.pub"),
      path.join(home, ".tauri", "nextn.key.pub"),
    ];
    // Also respect TAURI_SIGNING_PRIVATE_KEY_PATH sibling (the .pub is
    // the same basename with .pub appended).
    const signingPath = process.env.TAURI_SIGNING_PRIVATE_KEY_PATH;
    if (signingPath) candidates.unshift(`${signingPath}.pub`);

    let onDiskPubkey: string | null = null;
    let onDiskPath: string | null = null;
    for (const c of candidates) {
      if (fs.existsSync(c)) {
        onDiskPubkey = fs.readFileSync(c, "utf8").trim();
        onDiskPath = c;
        break;
      }
    }
    // Skip the assertion if no local key exists (CI without the secret
    // mounted, or a contributor without a generated key). The other
    // tests above still pin the contract; this one is just an extra
    // drift guard for the local-machine workflow.
    if (!onDiskPubkey) {
      console.warn(
        `updater pubkey drift check skipped: no .pub file found in ${candidates.join(", ")}`,
      );
      return;
    }
    expect(onDiskPubkey).toBe(pubkey);
    // The test should report which file was matched so a future failure
    // surfaces the right path immediately.
    console.log(`updater pubkey matched against ${onDiskPath}`);
  });
});
