/**
 * Video-Derived Fixture: both-players-creatures
 * Description: Both sides have creatures
 * Fixture ID: both-players-creatures
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const both_players_creatures = {
  id: "both-players-creatures",
  name: "both-players-creatures",
  description: "Both sides have creatures",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Grizzly Bears",
        is_tapped: false,
        power: 2,
        toughness: 2,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Llanowar Elves",
        is_tapped: false,
        power: 1,
        toughness: 1,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 5,
    graveyard: [],
    stack: [],
    phase: "begin_combat",
    turn_number: 3,
  },
  expectedBehaviors: [
    "Game state should serialize without errors",
    "Player life totals should be valid integers",
    "Battlefield arrays should contain valid card entries",
    "Hand size should be a non-negative integer",
    "Phase should be a recognized game phase string",
    "Turn number should be a positive integer",
    "Graveyard should contain card name strings",
    "Stack should contain spell name strings or be empty",
  ],
};

describe("Video-Derived Fixture: both-players-creatures", () => {
  it("loads game state successfully", () => {
    expect(typeof both_players_creatures.gameState).toBe("object");
    expect(both_players_creatures.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(both_players_creatures.gameState.player_life)).toBe(
      true,
    );
    expect(
      Number.isInteger(both_players_creatures.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(both_players_creatures.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(both_players_creatures.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof both_players_creatures.gameState.turn_number).toBe("number");
    expect(Number.isInteger(both_players_creatures.gameState.turn_number)).toBe(
      true,
    );
    expect(both_players_creatures.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof both_players_creatures.gameState.phase).toBe("string");
    expect(both_players_creatures.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(both_players_creatures.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(both_players_creatures.gameState);
  });

  for (const behavior of both_players_creatures.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, both_players_creatures.gameState);
    });
  }
});
