/**
 * Video-Derived Fixture: card-in-graveyard
 * Description: Cards in graveyard after spell
 * Fixture ID: card-in-graveyard
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const card_in_graveyard = {
  id: "card-in-graveyard",
  name: "card-in-graveyard",
  description: "Cards in graveyard after spell",
  gameState: {
    player_life: 20,
    opponent_life: 17,
    battlefield_player: [
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [],
    hand_size: 5,
    graveyard: ["Lightning Bolt", "Mountain"],
    stack: [],
    phase: "end",
    turn_number: 1,
  },
  expectedBehaviors: [
    "Game state should serialize without errors",
    "Player life totals should be valid integers",
    "Battlefield arrays should contain valid card entries",
    "Hand size should be a non-negative integer",
    "Phase should be a recognized game phase string",
    "Turn number should be a positive integer",
    "Graveyard should contain card name strings",
    "Stack should contain spell name strings or be empty",
  ],
};

describe("Video-Derived Fixture: card-in-graveyard", () => {
  it("loads game state successfully", () => {
    expect(typeof card_in_graveyard.gameState).toBe("object");
    expect(card_in_graveyard.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(card_in_graveyard.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(card_in_graveyard.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(card_in_graveyard.gameState.battlefield_player)).toBe(
      true,
    );
    expect(
      Array.isArray(card_in_graveyard.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof card_in_graveyard.gameState.turn_number).toBe("number");
    expect(Number.isInteger(card_in_graveyard.gameState.turn_number)).toBe(
      true,
    );
    expect(card_in_graveyard.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof card_in_graveyard.gameState.phase).toBe("string");
    expect(card_in_graveyard.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(card_in_graveyard.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(card_in_graveyard.gameState);
  });

  for (const behavior of card_in_graveyard.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, card_in_graveyard.gameState);
    });
  }
});
