/**
 * Video-Derived Fixture: cast-cryptic-command-on-stack
 * Description: Cryptic Command (modal instant) cast and on the stack — exercises spell-casting/cast.ts legality checks and the castSpell pipeline for a modal spell
 * Fixture ID: cast-cryptic-command-on-stack
 * Source: video-derived (issue #1801 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/generate-test-fixture.ts (issue #1801).
 * Each "validates behavior" it-block delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const cast_cryptic_command_on_stack = {
  id: "cast-cryptic-command-on-stack",
  name: "cast-cryptic-command-on-stack",
  description:
    "Cryptic Command (modal instant) cast and on the stack — exercises spell-casting/cast.ts legality checks and the castSpell pipeline for a modal spell",
  gameState: {
    player_life: 17,
    opponent_life: 18,
    battlefield_player: [
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Snow-Covered Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Snow-Covered Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Flooded Strand",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Goblin Guide",
        is_tapped: false,
        power: 1,
        toughness: 2,
      },
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 5,
    graveyard: [],
    stack: ["Cryptic Command"],
    phase: "declare_attackers",
    turn_number: 4,
  },
  expectedBehaviors: [
    "Spell cast should appear on stack in cast order",
    "Casting player should have priority to choose modes",
    "Tapped mana sources should remain tapped after cast",
    "Stack should hold the active spell as the topmost object",
    "Battlefield state should be internally consistent",
    "Phase should be a recognized game phase string",
    "Hand size should reflect the cast card leaving hand",
    "Mana availability should match untapped lands after payment",
  ],
};

describe("Video-Derived Fixture: cast-cryptic-command-on-stack", () => {
  it("loads game state successfully", () => {
    expect(typeof cast_cryptic_command_on_stack.gameState).toBe("object");
    expect(cast_cryptic_command_on_stack.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(cast_cryptic_command_on_stack.gameState.player_life),
    ).toBe(true);
    expect(
      Number.isInteger(cast_cryptic_command_on_stack.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(cast_cryptic_command_on_stack.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(
        cast_cryptic_command_on_stack.gameState.battlefield_opponent,
      ),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof cast_cryptic_command_on_stack.gameState.turn_number).toBe(
      "number",
    );
    expect(
      Number.isInteger(cast_cryptic_command_on_stack.gameState.turn_number),
    ).toBe(true);
    expect(cast_cryptic_command_on_stack.gameState.turn_number).toBeGreaterThan(
      0,
    );
    expect(typeof cast_cryptic_command_on_stack.gameState.phase).toBe("string");
    expect(
      cast_cryptic_command_on_stack.gameState.phase.length,
    ).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(cast_cryptic_command_on_stack.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(cast_cryptic_command_on_stack.gameState);
  });

  for (const behavior of cast_cryptic_command_on_stack.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, cast_cryptic_command_on_stack.gameState);
    });
  }
});
