/**
 * Video-Derived Fixture: chalice-of-the-void
 * Description: Chalice stopping one-drops
 * Fixture ID: chalice-of-the-void
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const chalice_of_the_void = {
  id: "chalice-of-the-void",
  name: "chalice-of-the-void",
  description: "Chalice stopping one-drops",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Chalice of the Void",
        is_tapped: false,
        power: 0,
        toughness: 0,
        counters: {
          charge: 1,
        },
      },
      {
        name: "Ancient Tomb",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "City of Traitors",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 5,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 2,
  },
  expectedBehaviors: [
    "Complex combat should resolve damage correctly",
    "Multiple stack items should resolve in order",
    "Commander damage should accumulate",
    "Land count should match turn constraints",
    "Board wipe should clear creature types only",
    "Mana availability should match untapped lands",
    "Proliferate should increment all counter types",
  ],
};

describe("Video-Derived Fixture: chalice-of-the-void", () => {
  it("loads game state successfully", () => {
    expect(typeof chalice_of_the_void.gameState).toBe("object");
    expect(chalice_of_the_void.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(chalice_of_the_void.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(chalice_of_the_void.gameState.opponent_life)).toBe(
      true,
    );
    expect(
      Array.isArray(chalice_of_the_void.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(chalice_of_the_void.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof chalice_of_the_void.gameState.turn_number).toBe("number");
    expect(Number.isInteger(chalice_of_the_void.gameState.turn_number)).toBe(
      true,
    );
    expect(chalice_of_the_void.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof chalice_of_the_void.gameState.phase).toBe("string");
    expect(chalice_of_the_void.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(chalice_of_the_void.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(chalice_of_the_void.gameState);
  });

  for (const behavior of chalice_of_the_void.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, chalice_of_the_void.gameState);
    });
  }
});
