/**
 * Video-Derived Fixture: combat-trample-multi-blocker-order
 * Description: Trample attacker blocked by two creatures — exercises combat.ts damage assignment order with multiple blockers (CR 702.19 trample, CR 510 combat damage step)
 * Fixture ID: combat-trample-multi-blocker-order
 * Source: video-derived (issue #1801 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/generate-test-fixture.ts (issue #1801).
 * Each "validates behavior" it-block delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const combat_trample_multi_blocker_order = {
  id: "combat-trample-multi-blocker-order",
  name: "combat-trample-multi-blocker-order",
  description:
    "Trample attacker blocked by two creatures — exercises combat.ts damage assignment order with multiple blockers (CR 702.19 trample, CR 510 combat damage step)",
  gameState: {
    player_life: 14,
    opponent_life: 8,
    battlefield_player: [
      {
        name: "Questing Beast",
        is_tapped: true,
        power: 4,
        toughness: 4,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Tarmogoyf",
        is_tapped: true,
        power: 4,
        toughness: 5,
      },
      {
        name: "Llanowar Elves",
        is_tapped: true,
        power: 1,
        toughness: 1,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 5,
    graveyard: [],
    stack: [],
    phase: "combat_damage",
    turn_number: 6,
  },
  expectedBehaviors: [
    "Trample damage assignment order should be observed (CR 702.19)",
    "All blocking creatures should receive lethal damage before trample over",
    "Attacker should remain tapped through combat_damage phase",
    "Multi-blocker damage should follow assignment order",
    "Battlefield state should be internally consistent",
    "Hand size should be a non-negative integer",
    "Phase should be a recognized game phase string",
    "Turn number should be a positive integer",
  ],
};

describe("Video-Derived Fixture: combat-trample-multi-blocker-order", () => {
  it("loads game state successfully", () => {
    expect(typeof combat_trample_multi_blocker_order.gameState).toBe("object");
    expect(combat_trample_multi_blocker_order.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(
        combat_trample_multi_blocker_order.gameState.player_life,
      ),
    ).toBe(true);
    expect(
      Number.isInteger(
        combat_trample_multi_blocker_order.gameState.opponent_life,
      ),
    ).toBe(true);
    expect(
      Array.isArray(
        combat_trample_multi_blocker_order.gameState.battlefield_player,
      ),
    ).toBe(true);
    expect(
      Array.isArray(
        combat_trample_multi_blocker_order.gameState.battlefield_opponent,
      ),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(
      typeof combat_trample_multi_blocker_order.gameState.turn_number,
    ).toBe("number");
    expect(
      Number.isInteger(
        combat_trample_multi_blocker_order.gameState.turn_number,
      ),
    ).toBe(true);
    expect(
      combat_trample_multi_blocker_order.gameState.turn_number,
    ).toBeGreaterThan(0);
    expect(typeof combat_trample_multi_blocker_order.gameState.phase).toBe(
      "string",
    );
    expect(
      combat_trample_multi_blocker_order.gameState.phase.length,
    ).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(
      combat_trample_multi_blocker_order.gameState,
    );
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(combat_trample_multi_blocker_order.gameState);
  });

  for (const behavior of combat_trample_multi_blocker_order.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, combat_trample_multi_blocker_order.gameState);
    });
  }
});
