/**
 * Video-Derived Fixture: combat-attackers-declared
 * Description: Attackers declared
 * Fixture ID: combat-attackers-declared
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const combat_attackers_declared = {
  id: "combat-attackers-declared",
  name: "combat-attackers-declared",
  description: "Attackers declared",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Grizzly Bears",
        is_tapped: true,
        power: 2,
        toughness: 2,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Llanowar Elves",
        is_tapped: false,
        power: 1,
        toughness: 1,
      },
    ],
    hand_size: 4,
    graveyard: [],
    stack: [],
    phase: "declare_attackers",
    turn_number: 3,
  },
  expectedBehaviors: [
    "Tapped permanents should be correctly flagged",
    "Stack spells should reflect active priority",
    "Counter tracking should serialize correctly",
    "Life total changes should match expected damage",
    "Phase transitions should follow valid order",
    "Face-down cards should hide identity",
    "Graveyard interaction targets should be valid",
  ],
};

describe("Video-Derived Fixture: combat-attackers-declared", () => {
  it("loads game state successfully", () => {
    expect(typeof combat_attackers_declared.gameState).toBe("object");
    expect(combat_attackers_declared.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(combat_attackers_declared.gameState.player_life),
    ).toBe(true);
    expect(
      Number.isInteger(combat_attackers_declared.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(combat_attackers_declared.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(combat_attackers_declared.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof combat_attackers_declared.gameState.turn_number).toBe(
      "number",
    );
    expect(
      Number.isInteger(combat_attackers_declared.gameState.turn_number),
    ).toBe(true);
    expect(combat_attackers_declared.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof combat_attackers_declared.gameState.phase).toBe("string");
    expect(combat_attackers_declared.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(combat_attackers_declared.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(combat_attackers_declared.gameState);
  });

  for (const behavior of combat_attackers_declared.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, combat_attackers_declared.gameState);
    });
  }
});
