/**
 * Video-Derived Fixture: commander-damage-race
 * Description: Commander damage race
 * Fixture ID: commander-damage-race
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const commander_damage_race = {
  id: "commander-damage-race",
  name: "commander-damage-race",
  description: "Commander damage race",
  gameState: {
    player_life: 40,
    opponent_life: 40,
    battlefield_player: [
      {
        name: "Kroxa, Titan of Death Hunger",
        is_tapped: false,
        power: 6,
        toughness: 6,
      },
      {
        name: "Bayou",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Swamp",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Omnath, Locus of Creation",
        is_tapped: false,
        power: 3,
        toughness: 3,
      },
      {
        name: "Taiga",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Savannah",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 3,
    graveyard: ["Fatal Push", "Veil of Summer"],
    stack: [],
    phase: "begin_combat",
    turn_number: 8,
  },
  expectedBehaviors: [
    "Complex combat should resolve damage correctly",
    "Multiple stack items should resolve in order",
    "Commander damage should accumulate",
    "Land count should match turn constraints",
    "Board wipe should clear creature types only",
    "Mana availability should match untapped lands",
    "Proliferate should increment all counter types",
  ],
};

describe("Video-Derived Fixture: commander-damage-race", () => {
  it("loads game state successfully", () => {
    expect(typeof commander_damage_race.gameState).toBe("object");
    expect(commander_damage_race.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(commander_damage_race.gameState.player_life)).toBe(
      true,
    );
    expect(
      Number.isInteger(commander_damage_race.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(commander_damage_race.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(commander_damage_race.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof commander_damage_race.gameState.turn_number).toBe("number");
    expect(Number.isInteger(commander_damage_race.gameState.turn_number)).toBe(
      true,
    );
    expect(commander_damage_race.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof commander_damage_race.gameState.phase).toBe("string");
    expect(commander_damage_race.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(commander_damage_race.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(commander_damage_race.gameState);
  });

  for (const behavior of commander_damage_race.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, commander_damage_race.gameState);
    });
  }
});
