/**
 * Video-Derived Fixture: complex-combat-multi-blocker
 * Description: Multiple blockers
 * Fixture ID: complex-combat-multi-blocker
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const complex_combat_multi_blocker = {
  id: "complex-combat-multi-blocker",
  name: "complex-combat-multi-blocker",
  description: "Multiple blockers",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Tarmogoyf",
        is_tapped: true,
        power: 4,
        toughness: 5,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Grizzly Bears",
        is_tapped: true,
        power: 2,
        toughness: 2,
      },
      {
        name: "Birds of Paradise",
        is_tapped: true,
        power: 0,
        toughness: 1,
      },
      {
        name: "Llanowar Elves",
        is_tapped: false,
        power: 1,
        toughness: 1,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 3,
    graveyard: [],
    stack: [],
    phase: "declare_blockers",
    turn_number: 5,
  },
  expectedBehaviors: [
    "The One Ring protection should prevent damage",
    "Sheoldred triggers should fire on each upkeep",
    "Orcish Bowmasters should ping on non-creature cast",
    "Multi-blocker damage should follow assignment order",
    "End-step timing windows should be enforced",
    "Priority should pass correctly between players",
    "Replacement effects should chain correctly",
    "Late-game state should be internally consistent",
  ],
};

describe("Video-Derived Fixture: complex-combat-multi-blocker", () => {
  it("loads game state successfully", () => {
    expect(typeof complex_combat_multi_blocker.gameState).toBe("object");
    expect(complex_combat_multi_blocker.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(complex_combat_multi_blocker.gameState.player_life),
    ).toBe(true);
    expect(
      Number.isInteger(complex_combat_multi_blocker.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(complex_combat_multi_blocker.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(
        complex_combat_multi_blocker.gameState.battlefield_opponent,
      ),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof complex_combat_multi_blocker.gameState.turn_number).toBe(
      "number",
    );
    expect(
      Number.isInteger(complex_combat_multi_blocker.gameState.turn_number),
    ).toBe(true);
    expect(complex_combat_multi_blocker.gameState.turn_number).toBeGreaterThan(
      0,
    );
    expect(typeof complex_combat_multi_blocker.gameState.phase).toBe("string");
    expect(complex_combat_multi_blocker.gameState.phase.length).toBeGreaterThan(
      0,
    );
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(complex_combat_multi_blocker.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(complex_combat_multi_blocker.gameState);
  });

  for (const behavior of complex_combat_multi_blocker.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, complex_combat_multi_blocker.gameState);
    });
  }
});
