/**
 * Video-Derived Fixture: complex-board-state
 * Description: Complex board many permanents
 * Fixture ID: complex-board-state
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const complex_board_state = {
  id: "complex-board-state",
  name: "complex-board-state",
  description: "Complex board many permanents",
  gameState: {
    player_life: 15,
    opponent_life: 12,
    battlefield_player: [
      {
        name: "Sol Ring",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Birds of Paradise",
        is_tapped: false,
        power: 0,
        toughness: 1,
      },
      {
        name: "Tarmogoyf",
        is_tapped: false,
        power: 4,
        toughness: 5,
      },
      {
        name: "Snapcaster Mage",
        is_tapped: true,
        power: 2,
        toughness: 1,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Delver of Secrets",
        is_tapped: false,
        power: 3,
        toughness: 2,
        counters: {
          "+1/+1": 1,
        },
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 2,
    graveyard: ["Lightning Bolt", "Ponder", "Fatal Push"],
    stack: [],
    phase: "main",
    turn_number: 7,
  },
  expectedBehaviors: [
    "Complex combat should resolve damage correctly",
    "Multiple stack items should resolve in order",
    "Commander damage should accumulate",
    "Land count should match turn constraints",
    "Board wipe should clear creature types only",
    "Mana availability should match untapped lands",
    "Proliferate should increment all counter types",
  ],
};

describe("Video-Derived Fixture: complex-board-state", () => {
  it("loads game state successfully", () => {
    expect(typeof complex_board_state.gameState).toBe("object");
    expect(complex_board_state.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(complex_board_state.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(complex_board_state.gameState.opponent_life)).toBe(
      true,
    );
    expect(
      Array.isArray(complex_board_state.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(complex_board_state.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof complex_board_state.gameState.turn_number).toBe("number");
    expect(Number.isInteger(complex_board_state.gameState.turn_number)).toBe(
      true,
    );
    expect(complex_board_state.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof complex_board_state.gameState.phase).toBe("string");
    expect(complex_board_state.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(complex_board_state.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(complex_board_state.gameState);
  });

  for (const behavior of complex_board_state.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, complex_board_state.gameState);
    });
  }
});
