/**
 * Video-Derived Fixture: creature-with-counters
 * Description: Creature with +1/+1 counters
 * Fixture ID: creature-with-counters
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const creature_with_counters = {
  id: "creature-with-counters",
  name: "creature-with-counters",
  description: "Creature with +1/+1 counters",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Tarmogoyf",
        is_tapped: false,
        power: 5,
        toughness: 6,
        counters: {
          "+1/+1": 1,
        },
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Plains",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 4,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 5,
  },
  expectedBehaviors: [
    "Tapped permanents should be correctly flagged",
    "Stack spells should reflect active priority",
    "Counter tracking should serialize correctly",
    "Life total changes should match expected damage",
    "Phase transitions should follow valid order",
    "Face-down cards should hide identity",
    "Graveyard interaction targets should be valid",
  ],
};

describe("Video-Derived Fixture: creature-with-counters", () => {
  it("loads game state successfully", () => {
    expect(typeof creature_with_counters.gameState).toBe("object");
    expect(creature_with_counters.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(creature_with_counters.gameState.player_life)).toBe(
      true,
    );
    expect(
      Number.isInteger(creature_with_counters.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(creature_with_counters.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(creature_with_counters.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof creature_with_counters.gameState.turn_number).toBe("number");
    expect(Number.isInteger(creature_with_counters.gameState.turn_number)).toBe(
      true,
    );
    expect(creature_with_counters.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof creature_with_counters.gameState.phase).toBe("string");
    expect(creature_with_counters.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(creature_with_counters.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(creature_with_counters.gameState);
  });

  for (const behavior of creature_with_counters.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, creature_with_counters.gameState);
    });
  }
});
