/**
 * Video-Derived Fixture: draw-spell-cast
 * Description: Brainstorm cast
 * Fixture ID: draw-spell-cast
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const draw_spell_cast = {
  id: "draw-spell-cast",
  name: "draw-spell-cast",
  description: "Brainstorm cast",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 6,
    graveyard: ["Brainstorm"],
    stack: [],
    phase: "main",
    turn_number: 3,
  },
  expectedBehaviors: [
    "Tapped permanents should be correctly flagged",
    "Stack spells should reflect active priority",
    "Counter tracking should serialize correctly",
    "Life total changes should match expected damage",
    "Phase transitions should follow valid order",
    "Face-down cards should hide identity",
    "Graveyard interaction targets should be valid",
  ],
};

describe("Video-Derived Fixture: draw-spell-cast", () => {
  it("loads game state successfully", () => {
    expect(typeof draw_spell_cast.gameState).toBe("object");
    expect(draw_spell_cast.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(draw_spell_cast.gameState.player_life)).toBe(true);
    expect(Number.isInteger(draw_spell_cast.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(draw_spell_cast.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(draw_spell_cast.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof draw_spell_cast.gameState.turn_number).toBe("number");
    expect(Number.isInteger(draw_spell_cast.gameState.turn_number)).toBe(true);
    expect(draw_spell_cast.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof draw_spell_cast.gameState.phase).toBe("string");
    expect(draw_spell_cast.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(draw_spell_cast.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(draw_spell_cast.gameState);
  });

  for (const behavior of draw_spell_cast.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, draw_spell_cast.gameState);
    });
  }
});
