/**
 * Video-Derived Fixture: empty-board-opening
 * Description: Empty board opening hand state
 * Fixture ID: empty-board-opening
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const empty_board_opening = {
  id: "empty-board-opening",
  name: "empty-board-opening",
  description: "Empty board opening hand state",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [],
    battlefield_opponent: [],
    hand_size: 7,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 1,
  },
  expectedBehaviors: [
    "Game state should serialize without errors",
    "Player life totals should be valid integers",
    "Battlefield arrays should contain valid card entries",
    "Hand size should be a non-negative integer",
    "Phase should be a recognized game phase string",
    "Turn number should be a positive integer",
    "Graveyard should contain card name strings",
    "Stack should contain spell name strings or be empty",
  ],
};

describe("Video-Derived Fixture: empty-board-opening", () => {
  it("loads game state successfully", () => {
    expect(typeof empty_board_opening.gameState).toBe("object");
    expect(empty_board_opening.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(empty_board_opening.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(empty_board_opening.gameState.opponent_life)).toBe(
      true,
    );
    expect(
      Array.isArray(empty_board_opening.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(empty_board_opening.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof empty_board_opening.gameState.turn_number).toBe("number");
    expect(Number.isInteger(empty_board_opening.gameState.turn_number)).toBe(
      true,
    );
    expect(empty_board_opening.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof empty_board_opening.gameState.phase).toBe("string");
    expect(empty_board_opening.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(empty_board_opening.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(empty_board_opening.gameState);
  });

  for (const behavior of empty_board_opening.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, empty_board_opening.gameState);
    });
  }
});
