/**
 * Video-Derived Fixture: end-step-response
 * Description: End step interaction
 * Fixture ID: end-step-response
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const end_step_response = {
  id: "end-step-response",
  name: "end-step-response",
  description: "End step interaction",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Snapcaster Mage",
        is_tapped: false,
        power: 2,
        toughness: 1,
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 3,
    graveyard: ["Lightning Bolt", "Brainstorm", "Ponder"],
    stack: [],
    phase: "end",
    turn_number: 5,
  },
  expectedBehaviors: [
    "The One Ring protection should prevent damage",
    "Sheoldred triggers should fire on each upkeep",
    "Orcish Bowmasters should ping on non-creature cast",
    "Multi-blocker damage should follow assignment order",
    "End-step timing windows should be enforced",
    "Priority should pass correctly between players",
    "Replacement effects should chain correctly",
    "Late-game state should be internally consistent",
  ],
};

describe("Video-Derived Fixture: end-step-response", () => {
  it("loads game state successfully", () => {
    expect(typeof end_step_response.gameState).toBe("object");
    expect(end_step_response.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(end_step_response.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(end_step_response.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(end_step_response.gameState.battlefield_player)).toBe(
      true,
    );
    expect(
      Array.isArray(end_step_response.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof end_step_response.gameState.turn_number).toBe("number");
    expect(Number.isInteger(end_step_response.gameState.turn_number)).toBe(
      true,
    );
    expect(end_step_response.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof end_step_response.gameState.phase).toBe("string");
    expect(end_step_response.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(end_step_response.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(end_step_response.gameState);
  });

  for (const behavior of end_step_response.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, end_step_response.gameState);
    });
  }
});
