/**
 * Video-Derived Fixture: equipment-attached
 * Description: Equipment on creature
 * Fixture ID: equipment-attached
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const equipment_attached = {
  id: "equipment-attached",
  name: "equipment-attached",
  description: "Equipment on creature",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Stoneforge Mystic",
        is_tapped: true,
        power: 3,
        toughness: 3,
      },
      {
        name: "Batterskull",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Plains",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [],
    hand_size: 4,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 4,
  },
  expectedBehaviors: [
    "Tapped permanents should be correctly flagged",
    "Stack spells should reflect active priority",
    "Counter tracking should serialize correctly",
    "Life total changes should match expected damage",
    "Phase transitions should follow valid order",
    "Face-down cards should hide identity",
    "Graveyard interaction targets should be valid",
  ],
};

describe("Video-Derived Fixture: equipment-attached", () => {
  it("loads game state successfully", () => {
    expect(typeof equipment_attached.gameState).toBe("object");
    expect(equipment_attached.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(equipment_attached.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(equipment_attached.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(equipment_attached.gameState.battlefield_player)).toBe(
      true,
    );
    expect(
      Array.isArray(equipment_attached.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof equipment_attached.gameState.turn_number).toBe("number");
    expect(Number.isInteger(equipment_attached.gameState.turn_number)).toBe(
      true,
    );
    expect(equipment_attached.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof equipment_attached.gameState.phase).toBe("string");
    expect(equipment_attached.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(equipment_attached.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(equipment_attached.gameState);
  });

  for (const behavior of equipment_attached.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, equipment_attached.gameState);
    });
  }
});
