/**
 * Video-Derived Fixture: face-down-card
 * Description: Morph face-down card
 * Fixture ID: face-down-card
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const face_down_card = {
  id: "face-down-card",
  name: "face-down-card",
  description: "Morph face-down card",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Unknown Card",
        is_tapped: false,
        power: 2,
        toughness: 2,
        is_face_down: true,
      },
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [],
    hand_size: 4,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 3,
  },
  expectedBehaviors: [
    "Tapped permanents should be correctly flagged",
    "Stack spells should reflect active priority",
    "Counter tracking should serialize correctly",
    "Life total changes should match expected damage",
    "Phase transitions should follow valid order",
    "Face-down cards should hide identity",
    "Graveyard interaction targets should be valid",
  ],
};

describe("Video-Derived Fixture: face-down-card", () => {
  it("loads game state successfully", () => {
    expect(typeof face_down_card.gameState).toBe("object");
    expect(face_down_card.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(face_down_card.gameState.player_life)).toBe(true);
    expect(Number.isInteger(face_down_card.gameState.opponent_life)).toBe(true);
    expect(Array.isArray(face_down_card.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(face_down_card.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof face_down_card.gameState.turn_number).toBe("number");
    expect(Number.isInteger(face_down_card.gameState.turn_number)).toBe(true);
    expect(face_down_card.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof face_down_card.gameState.phase).toBe("string");
    expect(face_down_card.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(face_down_card.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(face_down_card.gameState);
  });

  for (const behavior of face_down_card.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, face_down_card.gameState);
    });
  }
});
