/**
 * Video-Derived Fixture: full-game-late-state
 * Description: Late game complex board
 * Fixture ID: full-game-late-state
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const full_game_late_state = {
  id: "full-game-late-state",
  name: "full-game-late-state",
  description: "Late game complex board",
  gameState: {
    player_life: 7,
    opponent_life: 4,
    battlefield_player: [
      {
        name: "Sheoldred, the Apocalypse",
        is_tapped: false,
        power: 4,
        toughness: 5,
      },
      {
        name: "Uro, Titan of Nature Wrath",
        is_tapped: false,
        power: 6,
        toughness: 6,
      },
      {
        name: "The One Ring",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Swamp",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Swamp",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Underground Sea",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Bayou",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Tarmogoyf",
        is_tapped: true,
        power: 6,
        toughness: 7,
        counters: {
          "+1/+1": 2,
        },
      },
      {
        name: "Snapcaster Mage",
        is_tapped: false,
        power: 2,
        toughness: 1,
      },
      {
        name: "Omnath, Locus of Creation",
        is_tapped: false,
        power: 3,
        toughness: 3,
      },
      {
        name: "Volcanic Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Taiga",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 1,
    graveyard: [
      "Lightning Bolt",
      "Brainstorm",
      "Ponder",
      "Force of Will",
      "Fatal Push",
      "Inquisition of Kozilek",
    ],
    stack: [],
    phase: "postcombat_main",
    turn_number: 12,
  },
  expectedBehaviors: [
    "The One Ring protection should prevent damage",
    "Sheoldred triggers should fire on each upkeep",
    "Orcish Bowmasters should ping on non-creature cast",
    "Multi-blocker damage should follow assignment order",
    "End-step timing windows should be enforced",
    "Priority should pass correctly between players",
    "Replacement effects should chain correctly",
    "Late-game state should be internally consistent",
  ],
};

describe("Video-Derived Fixture: full-game-late-state", () => {
  it("loads game state successfully", () => {
    expect(typeof full_game_late_state.gameState).toBe("object");
    expect(full_game_late_state.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(full_game_late_state.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(full_game_late_state.gameState.opponent_life)).toBe(
      true,
    );
    expect(
      Array.isArray(full_game_late_state.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(full_game_late_state.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof full_game_late_state.gameState.turn_number).toBe("number");
    expect(Number.isInteger(full_game_late_state.gameState.turn_number)).toBe(
      true,
    );
    expect(full_game_late_state.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof full_game_late_state.gameState.phase).toBe("string");
    expect(full_game_late_state.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(full_game_late_state.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(full_game_late_state.gameState);
  });

  for (const behavior of full_game_late_state.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, full_game_late_state.gameState);
    });
  }
});
