/**
 * Video-Derived Fixture: land-destruction
 * Description: After land destruction
 * Fixture ID: land-destruction
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const land_destruction = {
  id: "land-destruction",
  name: "land-destruction",
  description: "After land destruction",
  gameState: {
    player_life: 20,
    opponent_life: 16,
    battlefield_player: [
      {
        name: "Mountain",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Plains",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 5,
    graveyard: ["Stone Rain", "Forest"],
    stack: [],
    phase: "main",
    turn_number: 4,
  },
  expectedBehaviors: [
    "Complex combat should resolve damage correctly",
    "Multiple stack items should resolve in order",
    "Commander damage should accumulate",
    "Land count should match turn constraints",
    "Board wipe should clear creature types only",
    "Mana availability should match untapped lands",
    "Proliferate should increment all counter types",
  ],
};

describe("Video-Derived Fixture: land-destruction", () => {
  it("loads game state successfully", () => {
    expect(typeof land_destruction.gameState).toBe("object");
    expect(land_destruction.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(land_destruction.gameState.player_life)).toBe(true);
    expect(Number.isInteger(land_destruction.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(land_destruction.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(land_destruction.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof land_destruction.gameState.turn_number).toBe("number");
    expect(Number.isInteger(land_destruction.gameState.turn_number)).toBe(true);
    expect(land_destruction.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof land_destruction.gameState.phase).toBe("string");
    expect(land_destruction.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(land_destruction.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(land_destruction.gameState);
  });

  for (const behavior of land_destruction.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, land_destruction.gameState);
    });
  }
});
