/**
 * Video-Derived Fixture: life-loss-basic
 * Description: Player has taken damage
 * Fixture ID: life-loss-basic
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const life_loss_basic = {
  id: "life-loss-basic",
  name: "life-loss-basic",
  description: "Player has taken damage",
  gameState: {
    player_life: 16,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Mountain",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 4,
    graveyard: ["Lightning Bolt"],
    stack: [],
    phase: "main",
    turn_number: 2,
  },
  expectedBehaviors: [
    "Game state should serialize without errors",
    "Player life totals should be valid integers",
    "Battlefield arrays should contain valid card entries",
    "Hand size should be a non-negative integer",
    "Phase should be a recognized game phase string",
    "Turn number should be a positive integer",
    "Graveyard should contain card name strings",
    "Stack should contain spell name strings or be empty",
  ],
};

describe("Video-Derived Fixture: life-loss-basic", () => {
  it("loads game state successfully", () => {
    expect(typeof life_loss_basic.gameState).toBe("object");
    expect(life_loss_basic.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(life_loss_basic.gameState.player_life)).toBe(true);
    expect(Number.isInteger(life_loss_basic.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(life_loss_basic.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(life_loss_basic.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof life_loss_basic.gameState.turn_number).toBe("number");
    expect(Number.isInteger(life_loss_basic.gameState.turn_number)).toBe(true);
    expect(life_loss_basic.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof life_loss_basic.gameState.phase).toBe("string");
    expect(life_loss_basic.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(life_loss_basic.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(life_loss_basic.gameState);
  });

  for (const behavior of life_loss_basic.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, life_loss_basic.gameState);
    });
  }
});
