/**
 * Video-Derived Fixture: low-life-state
 * Description: Critical life total
 * Fixture ID: low-life-state
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const low_life_state = {
  id: "low-life-state",
  name: "low-life-state",
  description: "Critical life total",
  gameState: {
    player_life: 3,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Dark Confidant",
        is_tapped: false,
        power: 2,
        toughness: 1,
      },
      {
        name: "Swamp",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Swamp",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Mountain",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 2,
    graveyard: ["Thoughtseize", "Inquisition of Kozilek"],
    stack: [],
    phase: "end",
    turn_number: 5,
  },
  expectedBehaviors: [
    "Tapped permanents should be correctly flagged",
    "Stack spells should reflect active priority",
    "Counter tracking should serialize correctly",
    "Life total changes should match expected damage",
    "Phase transitions should follow valid order",
    "Face-down cards should hide identity",
    "Graveyard interaction targets should be valid",
  ],
};

describe("Video-Derived Fixture: low-life-state", () => {
  it("loads game state successfully", () => {
    expect(typeof low_life_state.gameState).toBe("object");
    expect(low_life_state.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(low_life_state.gameState.player_life)).toBe(true);
    expect(Number.isInteger(low_life_state.gameState.opponent_life)).toBe(true);
    expect(Array.isArray(low_life_state.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(low_life_state.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof low_life_state.gameState.turn_number).toBe("number");
    expect(Number.isInteger(low_life_state.gameState.turn_number)).toBe(true);
    expect(low_life_state.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof low_life_state.gameState.phase).toBe("string");
    expect(low_life_state.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(low_life_state.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(low_life_state.gameState);
  });

  for (const behavior of low_life_state.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, low_life_state.gameState);
    });
  }
});
