/**
 * Video-Derived Fixture: mana-screw-state
 * Description: Few lands many spells
 * Fixture ID: mana-screw-state
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const mana_screw_state = {
  id: "mana-screw-state",
  name: "mana-screw-state",
  description: "Few lands many spells",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Volcanic Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 6,
    graveyard: ["Brainstorm"],
    stack: [],
    phase: "draw",
    turn_number: 5,
  },
  expectedBehaviors: [
    "Complex combat should resolve damage correctly",
    "Multiple stack items should resolve in order",
    "Commander damage should accumulate",
    "Land count should match turn constraints",
    "Board wipe should clear creature types only",
    "Mana availability should match untapped lands",
    "Proliferate should increment all counter types",
  ],
};

describe("Video-Derived Fixture: mana-screw-state", () => {
  it("loads game state successfully", () => {
    expect(typeof mana_screw_state.gameState).toBe("object");
    expect(mana_screw_state.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(mana_screw_state.gameState.player_life)).toBe(true);
    expect(Number.isInteger(mana_screw_state.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(mana_screw_state.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(mana_screw_state.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof mana_screw_state.gameState.turn_number).toBe("number");
    expect(Number.isInteger(mana_screw_state.gameState.turn_number)).toBe(true);
    expect(mana_screw_state.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof mana_screw_state.gameState.phase).toBe("string");
    expect(mana_screw_state.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(mana_screw_state.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(mana_screw_state.gameState);
  });

  for (const behavior of mana_screw_state.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, mana_screw_state.gameState);
    });
  }
});
