/**
 * Video-Derived Fixture: mana-flood-state
 * Description: Many lands few spells
 * Fixture ID: mana-flood-state
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const mana_flood_state = {
  id: "mana-flood-state",
  name: "mana-flood-state",
  description: "Many lands few spells",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 1,
    graveyard: [],
    stack: [],
    phase: "end",
    turn_number: 10,
  },
  expectedBehaviors: [
    "Complex combat should resolve damage correctly",
    "Multiple stack items should resolve in order",
    "Commander damage should accumulate",
    "Land count should match turn constraints",
    "Board wipe should clear creature types only",
    "Mana availability should match untapped lands",
    "Proliferate should increment all counter types",
  ],
};

describe("Video-Derived Fixture: mana-flood-state", () => {
  it("loads game state successfully", () => {
    expect(typeof mana_flood_state.gameState).toBe("object");
    expect(mana_flood_state.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(mana_flood_state.gameState.player_life)).toBe(true);
    expect(Number.isInteger(mana_flood_state.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(mana_flood_state.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(mana_flood_state.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof mana_flood_state.gameState.turn_number).toBe("number");
    expect(Number.isInteger(mana_flood_state.gameState.turn_number)).toBe(true);
    expect(mana_flood_state.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof mana_flood_state.gameState.phase).toBe("string");
    expect(mana_flood_state.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(mana_flood_state.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(mana_flood_state.gameState);
  });

  for (const behavior of mana_flood_state.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, mana_flood_state.gameState);
    });
  }
});
