/**
 * Video-Derived Fixture: modal-choose-two-decision
 * Description: Modal choose-two spell on the stack waiting for mode selection — exercises spell-casting/choices.ts createChooseTwoModeChoice() (CR 700.2) and waiting-choice resolution
 * Fixture ID: modal-choose-two-decision
 * Source: video-derived (issue #1801 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/generate-test-fixture.ts (issue #1801).
 * Each "validates behavior" it-block delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const modal_choose_two_decision = {
  id: "modal-choose-two-decision",
  name: "modal-choose-two-decision",
  description:
    "Modal choose-two spell on the stack waiting for mode selection — exercises spell-casting/choices.ts createChooseTwoModeChoice() (CR 700.2) and waiting-choice resolution",
  gameState: {
    player_life: 14,
    opponent_life: 16,
    battlefield_player: [
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Plains",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Hallowed Fountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Tarmogoyf",
        is_tapped: false,
        power: 4,
        toughness: 5,
      },
      {
        name: "Tropical Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 4,
    graveyard: [],
    stack: ["Supreme Verdict", "Cryptic Command"],
    phase: "begin_combat",
    turn_number: 6,
  },
  expectedBehaviors: [
    "Modal spell should wait for mode choice before resolution",
    "Casting player should have priority to choose modes",
    "Stack should hold the modal spell as the topmost object",
    "Tapped mana sources should be correctly flagged",
    "Battlefield state should be internally consistent",
    "Hand size should be a non-negative integer",
    "Phase should be a recognized game phase string",
    "Mana availability should match untapped lands after payment",
  ],
};

describe("Video-Derived Fixture: modal-choose-two-decision", () => {
  it("loads game state successfully", () => {
    expect(typeof modal_choose_two_decision.gameState).toBe("object");
    expect(modal_choose_two_decision.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(modal_choose_two_decision.gameState.player_life),
    ).toBe(true);
    expect(
      Number.isInteger(modal_choose_two_decision.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(modal_choose_two_decision.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(modal_choose_two_decision.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof modal_choose_two_decision.gameState.turn_number).toBe(
      "number",
    );
    expect(
      Number.isInteger(modal_choose_two_decision.gameState.turn_number),
    ).toBe(true);
    expect(modal_choose_two_decision.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof modal_choose_two_decision.gameState.phase).toBe("string");
    expect(modal_choose_two_decision.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(modal_choose_two_decision.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(modal_choose_two_decision.gameState);
  });

  for (const behavior of modal_choose_two_decision.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, modal_choose_two_decision.gameState);
    });
  }
});
