/**
 * Video-Derived Fixture: mulligan-decision
 * Description: Post-mulligan hand
 * Fixture ID: mulligan-decision
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const mulligan_decision = {
  id: "mulligan-decision",
  name: "mulligan-decision",
  description: "Post-mulligan hand",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [],
    battlefield_opponent: [],
    hand_size: 6,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 1,
  },
  expectedBehaviors: [
    "The One Ring protection should prevent damage",
    "Sheoldred triggers should fire on each upkeep",
    "Orcish Bowmasters should ping on non-creature cast",
    "Multi-blocker damage should follow assignment order",
    "End-step timing windows should be enforced",
    "Priority should pass correctly between players",
    "Replacement effects should chain correctly",
    "Late-game state should be internally consistent",
  ],
};

describe("Video-Derived Fixture: mulligan-decision", () => {
  it("loads game state successfully", () => {
    expect(typeof mulligan_decision.gameState).toBe("object");
    expect(mulligan_decision.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(mulligan_decision.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(mulligan_decision.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(mulligan_decision.gameState.battlefield_player)).toBe(
      true,
    );
    expect(
      Array.isArray(mulligan_decision.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof mulligan_decision.gameState.turn_number).toBe("number");
    expect(Number.isInteger(mulligan_decision.gameState.turn_number)).toBe(
      true,
    );
    expect(mulligan_decision.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof mulligan_decision.gameState.phase).toBe("string");
    expect(mulligan_decision.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(mulligan_decision.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(mulligan_decision.gameState);
  });

  for (const behavior of mulligan_decision.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, mulligan_decision.gameState);
    });
  }
});
