/**
 * Video-Derived Fixture: orcish-bowmasters-trigger
 * Description: Bowmasters pinging
 * Fixture ID: orcish-bowmasters-trigger
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const orcish_bowmasters_trigger = {
  id: "orcish-bowmasters-trigger",
  name: "orcish-bowmasters-trigger",
  description: "Bowmasters pinging",
  gameState: {
    player_life: 20,
    opponent_life: 18,
    battlefield_player: [
      {
        name: "Orcish Bowmasters",
        is_tapped: false,
        power: 1,
        toughness: 1,
      },
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 5,
    graveyard: [],
    stack: ["Orcish Bowmasters - trigger"],
    phase: "main",
    turn_number: 3,
  },
  expectedBehaviors: [
    "The One Ring protection should prevent damage",
    "Sheoldred triggers should fire on each upkeep",
    "Orcish Bowmasters should ping on non-creature cast",
    "Multi-blocker damage should follow assignment order",
    "End-step timing windows should be enforced",
    "Priority should pass correctly between players",
    "Replacement effects should chain correctly",
    "Late-game state should be internally consistent",
  ],
};

describe("Video-Derived Fixture: orcish-bowmasters-trigger", () => {
  it("loads game state successfully", () => {
    expect(typeof orcish_bowmasters_trigger.gameState).toBe("object");
    expect(orcish_bowmasters_trigger.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(orcish_bowmasters_trigger.gameState.player_life),
    ).toBe(true);
    expect(
      Number.isInteger(orcish_bowmasters_trigger.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(orcish_bowmasters_trigger.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(orcish_bowmasters_trigger.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof orcish_bowmasters_trigger.gameState.turn_number).toBe(
      "number",
    );
    expect(
      Number.isInteger(orcish_bowmasters_trigger.gameState.turn_number),
    ).toBe(true);
    expect(orcish_bowmasters_trigger.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof orcish_bowmasters_trigger.gameState.phase).toBe("string");
    expect(orcish_bowmasters_trigger.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(orcish_bowmasters_trigger.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(orcish_bowmasters_trigger.gameState);
  });

  for (const behavior of orcish_bowmasters_trigger.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, orcish_bowmasters_trigger.gameState);
    });
  }
});
