/**
 * Video-Derived Fixture: planeswalker-in-play
 * Description: Planeswalker on battlefield
 * Fixture ID: planeswalker-in-play
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const planeswalker_in_play = {
  id: "planeswalker-in-play",
  name: "planeswalker-in-play",
  description: "Planeswalker on battlefield",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Teferi, Time Raveler",
        is_tapped: false,
        power: 3,
        toughness: 4,
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Plains",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 3,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 4,
  },
  expectedBehaviors: [
    "Tapped permanents should be correctly flagged",
    "Stack spells should reflect active priority",
    "Counter tracking should serialize correctly",
    "Life total changes should match expected damage",
    "Phase transitions should follow valid order",
    "Face-down cards should hide identity",
    "Graveyard interaction targets should be valid",
  ],
};

describe("Video-Derived Fixture: planeswalker-in-play", () => {
  it("loads game state successfully", () => {
    expect(typeof planeswalker_in_play.gameState).toBe("object");
    expect(planeswalker_in_play.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(planeswalker_in_play.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(planeswalker_in_play.gameState.opponent_life)).toBe(
      true,
    );
    expect(
      Array.isArray(planeswalker_in_play.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(planeswalker_in_play.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof planeswalker_in_play.gameState.turn_number).toBe("number");
    expect(Number.isInteger(planeswalker_in_play.gameState.turn_number)).toBe(
      true,
    );
    expect(planeswalker_in_play.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof planeswalker_in_play.gameState.phase).toBe("string");
    expect(planeswalker_in_play.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(planeswalker_in_play.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(planeswalker_in_play.gameState);
  });

  for (const behavior of planeswalker_in_play.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, planeswalker_in_play.gameState);
    });
  }
});
