/**
 * Video-Derived Fixture: priority-pass-tracking
 * Description: Multiple priority passes
 * Fixture ID: priority-pass-tracking
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const priority_pass_tracking = {
  id: "priority-pass-tracking",
  name: "priority-pass-tracking",
  description: "Multiple priority passes",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 5,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 3,
  },
  expectedBehaviors: [
    "The One Ring protection should prevent damage",
    "Sheoldred triggers should fire on each upkeep",
    "Orcish Bowmasters should ping on non-creature cast",
    "Multi-blocker damage should follow assignment order",
    "End-step timing windows should be enforced",
    "Priority should pass correctly between players",
    "Replacement effects should chain correctly",
    "Late-game state should be internally consistent",
  ],
};

describe("Video-Derived Fixture: priority-pass-tracking", () => {
  it("loads game state successfully", () => {
    expect(typeof priority_pass_tracking.gameState).toBe("object");
    expect(priority_pass_tracking.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(priority_pass_tracking.gameState.player_life)).toBe(
      true,
    );
    expect(
      Number.isInteger(priority_pass_tracking.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(priority_pass_tracking.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(priority_pass_tracking.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof priority_pass_tracking.gameState.turn_number).toBe("number");
    expect(Number.isInteger(priority_pass_tracking.gameState.turn_number)).toBe(
      true,
    );
    expect(priority_pass_tracking.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof priority_pass_tracking.gameState.phase).toBe("string");
    expect(priority_pass_tracking.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(priority_pass_tracking.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(priority_pass_tracking.gameState);
  });

  for (const behavior of priority_pass_tracking.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, priority_pass_tracking.gameState);
    });
  }
});
