/**
 * Video-Derived Fixture: proliferate-board
 * Description: Proliferate counters
 * Fixture ID: proliferate-board
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const proliferate_board = {
  id: "proliferate-board",
  name: "proliferate-board",
  description: "Proliferate counters",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Tarmogoyf",
        is_tapped: false,
        power: 5,
        toughness: 6,
        counters: {
          "+1/+1": 1,
        },
      },
      {
        name: "Birds of Paradise",
        is_tapped: false,
        power: 0,
        toughness: 2,
        counters: {
          "+1/+1": 1,
        },
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [],
    hand_size: 4,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 5,
  },
  expectedBehaviors: [
    "Complex combat should resolve damage correctly",
    "Multiple stack items should resolve in order",
    "Commander damage should accumulate",
    "Land count should match turn constraints",
    "Board wipe should clear creature types only",
    "Mana availability should match untapped lands",
    "Proliferate should increment all counter types",
  ],
};

describe("Video-Derived Fixture: proliferate-board", () => {
  it("loads game state successfully", () => {
    expect(typeof proliferate_board.gameState).toBe("object");
    expect(proliferate_board.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(proliferate_board.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(proliferate_board.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(proliferate_board.gameState.battlefield_player)).toBe(
      true,
    );
    expect(
      Array.isArray(proliferate_board.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof proliferate_board.gameState.turn_number).toBe("number");
    expect(Number.isInteger(proliferate_board.gameState.turn_number)).toBe(
      true,
    );
    expect(proliferate_board.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof proliferate_board.gameState.phase).toBe("string");
    expect(proliferate_board.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(proliferate_board.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(proliferate_board.gameState);
  });

  for (const behavior of proliferate_board.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, proliferate_board.gameState);
    });
  }
});
