/**
 * Video-Derived Fixture: sba-legendary-rule-duplicate
 * Description: Two legendary creatures with the same name in play — exercises state-based-actions CR 704.5j (legendary rule) and the commander-zone redirect for Commander variant
 * Fixture ID: sba-legendary-rule-duplicate
 * Source: video-derived (issue #1801 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/generate-test-fixture.ts (issue #1801).
 * Each "validates behavior" it-block delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const sba_legendary_rule_duplicate = {
  id: "sba-legendary-rule-duplicate",
  name: "sba-legendary-rule-duplicate",
  description:
    "Two legendary creatures with the same name in play — exercises state-based-actions CR 704.5j (legendary rule) and the commander-zone redirect for Commander variant",
  gameState: {
    player_life: 22,
    opponent_life: 24,
    battlefield_player: [
      {
        name: "Ragavan, Nimble Pilferer",
        is_tapped: false,
        power: 2,
        toughness: 1,
      },
      {
        name: "Ragavan, Nimble Pilferer",
        is_tapped: false,
        power: 2,
        toughness: 1,
      },
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Arid Mesa",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Dragonlord Atarka",
        is_tapped: false,
        power: 8,
        toughness: 8,
      },
      {
        name: "Cinder Glade",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 4,
    graveyard: [],
    stack: [],
    phase: "upkeep",
    turn_number: 9,
  },
  expectedBehaviors: [
    "Legendary rule should flag duplicate legendary permanents (CR 704.5j)",
    "Only one copy of Ragavan, Nimble Pilferer should remain after SBAs",
    "Stack should be empty outside of SBA processing",
    "Battlefield state should be internally consistent",
    "Hand size should be a non-negative integer",
    "Phase should be a recognized game phase string",
    "Turn number should be a positive integer",
    "Commander redirect may apply in Commander variant",
  ],
};

describe("Video-Derived Fixture: sba-legendary-rule-duplicate", () => {
  it("loads game state successfully", () => {
    expect(typeof sba_legendary_rule_duplicate.gameState).toBe("object");
    expect(sba_legendary_rule_duplicate.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(sba_legendary_rule_duplicate.gameState.player_life),
    ).toBe(true);
    expect(
      Number.isInteger(sba_legendary_rule_duplicate.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(sba_legendary_rule_duplicate.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(
        sba_legendary_rule_duplicate.gameState.battlefield_opponent,
      ),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof sba_legendary_rule_duplicate.gameState.turn_number).toBe(
      "number",
    );
    expect(
      Number.isInteger(sba_legendary_rule_duplicate.gameState.turn_number),
    ).toBe(true);
    expect(sba_legendary_rule_duplicate.gameState.turn_number).toBeGreaterThan(
      0,
    );
    expect(typeof sba_legendary_rule_duplicate.gameState.phase).toBe("string");
    expect(sba_legendary_rule_duplicate.gameState.phase.length).toBeGreaterThan(
      0,
    );
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(sba_legendary_rule_duplicate.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(sba_legendary_rule_duplicate.gameState);
  });

  for (const behavior of sba_legendary_rule_duplicate.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, sba_legendary_rule_duplicate.gameState);
    });
  }
});
