/**
 * Video-Derived Fixture: sheoldred-graveyard-lock
 * Description: Sheoldred controlling
 * Fixture ID: sheoldred-graveyard-lock
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const sheoldred_graveyard_lock = {
  id: "sheoldred-graveyard-lock",
  name: "sheoldred-graveyard-lock",
  description: "Sheoldred controlling",
  gameState: {
    player_life: 18,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Sheoldred, the Apocalypse",
        is_tapped: false,
        power: 4,
        toughness: 5,
      },
      {
        name: "Swamp",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Swamp",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Swamp",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 5,
    graveyard: ["Grizzly Bears", "Ponder"],
    stack: [],
    phase: "upkeep",
    turn_number: 6,
  },
  expectedBehaviors: [
    "The One Ring protection should prevent damage",
    "Sheoldred triggers should fire on each upkeep",
    "Orcish Bowmasters should ping on non-creature cast",
    "Multi-blocker damage should follow assignment order",
    "End-step timing windows should be enforced",
    "Priority should pass correctly between players",
    "Replacement effects should chain correctly",
    "Late-game state should be internally consistent",
  ],
};

describe("Video-Derived Fixture: sheoldred-graveyard-lock", () => {
  it("loads game state successfully", () => {
    expect(typeof sheoldred_graveyard_lock.gameState).toBe("object");
    expect(sheoldred_graveyard_lock.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(sheoldred_graveyard_lock.gameState.player_life),
    ).toBe(true);
    expect(
      Number.isInteger(sheoldred_graveyard_lock.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(sheoldred_graveyard_lock.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(sheoldred_graveyard_lock.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof sheoldred_graveyard_lock.gameState.turn_number).toBe(
      "number",
    );
    expect(
      Number.isInteger(sheoldred_graveyard_lock.gameState.turn_number),
    ).toBe(true);
    expect(sheoldred_graveyard_lock.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof sheoldred_graveyard_lock.gameState.phase).toBe("string");
    expect(sheoldred_graveyard_lock.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(sheoldred_graveyard_lock.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(sheoldred_graveyard_lock.gameState);
  });

  for (const behavior of sheoldred_graveyard_lock.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, sheoldred_graveyard_lock.gameState);
    });
  }
});
