/**
 * Video-Derived Fixture: single-land-play
 * Description: First land played on turn 1
 * Fixture ID: single-land-play
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const single_land_play = {
  id: "single-land-play",
  name: "single-land-play",
  description: "First land played on turn 1",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [],
    hand_size: 6,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 1,
  },
  expectedBehaviors: [
    "Game state should serialize without errors",
    "Player life totals should be valid integers",
    "Battlefield arrays should contain valid card entries",
    "Hand size should be a non-negative integer",
    "Phase should be a recognized game phase string",
    "Turn number should be a positive integer",
    "Graveyard should contain card name strings",
    "Stack should contain spell name strings or be empty",
  ],
};

describe("Video-Derived Fixture: single-land-play", () => {
  it("loads game state successfully", () => {
    expect(typeof single_land_play.gameState).toBe("object");
    expect(single_land_play.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(single_land_play.gameState.player_life)).toBe(true);
    expect(Number.isInteger(single_land_play.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(single_land_play.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(single_land_play.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof single_land_play.gameState.turn_number).toBe("number");
    expect(Number.isInteger(single_land_play.gameState.turn_number)).toBe(true);
    expect(single_land_play.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof single_land_play.gameState.phase).toBe("string");
    expect(single_land_play.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(single_land_play.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(single_land_play.gameState);
  });

  for (const behavior of single_land_play.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, single_land_play.gameState);
    });
  }
});
