/**
 * Video-Derived Fixture: stack-mana-conflict
 * Description: Mana conflict on stack
 * Fixture ID: stack-mana-conflict
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const stack_mana_conflict = {
  id: "stack-mana-conflict",
  name: "stack-mana-conflict",
  description: "Mana conflict on stack",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Mountain",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Mountain",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 1,
    graveyard: [],
    stack: ["Force of Will", "Counterspell"],
    phase: "main",
    turn_number: 4,
  },
  expectedBehaviors: [
    "The One Ring protection should prevent damage",
    "Sheoldred triggers should fire on each upkeep",
    "Orcish Bowmasters should ping on non-creature cast",
    "Multi-blocker damage should follow assignment order",
    "End-step timing windows should be enforced",
    "Priority should pass correctly between players",
    "Replacement effects should chain correctly",
    "Late-game state should be internally consistent",
  ],
};

describe("Video-Derived Fixture: stack-mana-conflict", () => {
  it("loads game state successfully", () => {
    expect(typeof stack_mana_conflict.gameState).toBe("object");
    expect(stack_mana_conflict.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(stack_mana_conflict.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(stack_mana_conflict.gameState.opponent_life)).toBe(
      true,
    );
    expect(
      Array.isArray(stack_mana_conflict.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(stack_mana_conflict.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof stack_mana_conflict.gameState.turn_number).toBe("number");
    expect(Number.isInteger(stack_mana_conflict.gameState.turn_number)).toBe(
      true,
    );
    expect(stack_mana_conflict.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof stack_mana_conflict.gameState.phase).toBe("string");
    expect(stack_mana_conflict.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(stack_mana_conflict.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(stack_mana_conflict.gameState);
  });

  for (const behavior of stack_mana_conflict.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, stack_mana_conflict.gameState);
    });
  }
});
