/**
 * Video-Derived Fixture: storm-count-tracking
 * Description: Storm count high
 * Fixture ID: storm-count-tracking
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const storm_count_tracking = {
  id: "storm-count-tracking",
  name: "storm-count-tracking",
  description: "Storm count high",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 1,
    graveyard: [
      "Ponder",
      "Brainstorm",
      "Preordain",
      "Gitaxian Probe",
      "Gitaxian Probe",
    ],
    stack: ["Past in Flames"],
    phase: "main",
    turn_number: 4,
  },
  expectedBehaviors: [
    "Complex combat should resolve damage correctly",
    "Multiple stack items should resolve in order",
    "Commander damage should accumulate",
    "Land count should match turn constraints",
    "Board wipe should clear creature types only",
    "Mana availability should match untapped lands",
    "Proliferate should increment all counter types",
  ],
};

describe("Video-Derived Fixture: storm-count-tracking", () => {
  it("loads game state successfully", () => {
    expect(typeof storm_count_tracking.gameState).toBe("object");
    expect(storm_count_tracking.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(storm_count_tracking.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(storm_count_tracking.gameState.opponent_life)).toBe(
      true,
    );
    expect(
      Array.isArray(storm_count_tracking.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(storm_count_tracking.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof storm_count_tracking.gameState.turn_number).toBe("number");
    expect(Number.isInteger(storm_count_tracking.gameState.turn_number)).toBe(
      true,
    );
    expect(storm_count_tracking.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof storm_count_tracking.gameState.phase).toBe("string");
    expect(storm_count_tracking.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(storm_count_tracking.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(storm_count_tracking.gameState);
  });

  for (const behavior of storm_count_tracking.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, storm_count_tracking.gameState);
    });
  }
});
