/**
 * Video-Derived Fixture: swords-to-plowshares-exile
 * Description: Swords to Plowshares exile
 * Fixture ID: swords-to-plowshares-exile
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const swords_to_plowshares_exile = {
  id: "swords-to-plowshares-exile",
  name: "swords-to-plowshares-exile",
  description: "Swords to Plowshares exile",
  gameState: {
    player_life: 22,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Plains",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [],
    hand_size: 5,
    graveyard: ["Swords to Plowshares"],
    stack: [],
    phase: "main",
    turn_number: 3,
  },
  expectedBehaviors: [
    "Tapped permanents should be correctly flagged",
    "Stack spells should reflect active priority",
    "Counter tracking should serialize correctly",
    "Life total changes should match expected damage",
    "Phase transitions should follow valid order",
    "Face-down cards should hide identity",
    "Graveyard interaction targets should be valid",
  ],
};

describe("Video-Derived Fixture: swords-to-plowshares-exile", () => {
  it("loads game state successfully", () => {
    expect(typeof swords_to_plowshares_exile.gameState).toBe("object");
    expect(swords_to_plowshares_exile.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(swords_to_plowshares_exile.gameState.player_life),
    ).toBe(true);
    expect(
      Number.isInteger(swords_to_plowshares_exile.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(swords_to_plowshares_exile.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(swords_to_plowshares_exile.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof swords_to_plowshares_exile.gameState.turn_number).toBe(
      "number",
    );
    expect(
      Number.isInteger(swords_to_plowshares_exile.gameState.turn_number),
    ).toBe(true);
    expect(swords_to_plowshares_exile.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof swords_to_plowshares_exile.gameState.phase).toBe("string");
    expect(swords_to_plowshares_exile.gameState.phase.length).toBeGreaterThan(
      0,
    );
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(swords_to_plowshares_exile.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(swords_to_plowshares_exile.gameState);
  });

  for (const behavior of swords_to_plowshares_exile.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, swords_to_plowshares_exile.gameState);
    });
  }
});
