/**
 * Video-Derived Fixture: the-one-ring-trigger-stack
 * Description: One Ring triggers
 * Fixture ID: the-one-ring-trigger-stack
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const the_one_ring_trigger_stack = {
  id: "the-one-ring-trigger-stack",
  name: "the-one-ring-trigger-stack",
  description: "One Ring triggers",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "The One Ring",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Volcanic Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Underground Sea",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 4,
    graveyard: [],
    stack: [
      "The One Ring - Ring-bearer trigger",
      "The One Ring - draw trigger",
    ],
    phase: "main",
    turn_number: 4,
  },
  expectedBehaviors: [
    "The One Ring protection should prevent damage",
    "Sheoldred triggers should fire on each upkeep",
    "Orcish Bowmasters should ping on non-creature cast",
    "Multi-blocker damage should follow assignment order",
    "End-step timing windows should be enforced",
    "Priority should pass correctly between players",
    "Replacement effects should chain correctly",
    "Late-game state should be internally consistent",
  ],
};

describe("Video-Derived Fixture: the-one-ring-trigger-stack", () => {
  it("loads game state successfully", () => {
    expect(typeof the_one_ring_trigger_stack.gameState).toBe("object");
    expect(the_one_ring_trigger_stack.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(
      Number.isInteger(the_one_ring_trigger_stack.gameState.player_life),
    ).toBe(true);
    expect(
      Number.isInteger(the_one_ring_trigger_stack.gameState.opponent_life),
    ).toBe(true);
    expect(
      Array.isArray(the_one_ring_trigger_stack.gameState.battlefield_player),
    ).toBe(true);
    expect(
      Array.isArray(the_one_ring_trigger_stack.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof the_one_ring_trigger_stack.gameState.turn_number).toBe(
      "number",
    );
    expect(
      Number.isInteger(the_one_ring_trigger_stack.gameState.turn_number),
    ).toBe(true);
    expect(the_one_ring_trigger_stack.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof the_one_ring_trigger_stack.gameState.phase).toBe("string");
    expect(the_one_ring_trigger_stack.gameState.phase.length).toBeGreaterThan(
      0,
    );
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(the_one_ring_trigger_stack.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(the_one_ring_trigger_stack.gameState);
  });

  for (const behavior of the_one_ring_trigger_stack.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, the_one_ring_trigger_stack.gameState);
    });
  }
});
