/**
 * Video-Derived Fixture: token-generation
 * Description: Token from ability
 * Fixture ID: token-generation
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const token_generation = {
  id: "token-generation",
  name: "token-generation",
  description: "Token from ability",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Ragavan",
        is_tapped: true,
        power: 2,
        toughness: 1,
      },
      {
        name: "Mountain",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Treasure Token",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [],
    hand_size: 4,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 3,
  },
  expectedBehaviors: [
    "Tapped permanents should be correctly flagged",
    "Stack spells should reflect active priority",
    "Counter tracking should serialize correctly",
    "Life total changes should match expected damage",
    "Phase transitions should follow valid order",
    "Face-down cards should hide identity",
    "Graveyard interaction targets should be valid",
  ],
};

describe("Video-Derived Fixture: token-generation", () => {
  it("loads game state successfully", () => {
    expect(typeof token_generation.gameState).toBe("object");
    expect(token_generation.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(token_generation.gameState.player_life)).toBe(true);
    expect(Number.isInteger(token_generation.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(token_generation.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(token_generation.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof token_generation.gameState.turn_number).toBe("number");
    expect(Number.isInteger(token_generation.gameState.turn_number)).toBe(true);
    expect(token_generation.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof token_generation.gameState.phase).toBe("string");
    expect(token_generation.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(token_generation.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(token_generation.gameState);
  });

  for (const behavior of token_generation.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, token_generation.gameState);
    });
  }
});
