/**
 * Video-Derived Fixture: topdeck-mode
 * Description: No cards in hand
 * Fixture ID: topdeck-mode
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const topdeck_mode = {
  id: "topdeck-mode",
  name: "topdeck-mode",
  description: "No cards in hand",
  gameState: {
    player_life: 5,
    opponent_life: 12,
    battlefield_player: [
      {
        name: "Tarmogoyf",
        is_tapped: false,
        power: 4,
        toughness: 5,
      },
      {
        name: "Volcanic Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Underground Sea",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [
      {
        name: "Delver of Secrets",
        is_tapped: false,
        power: 3,
        toughness: 2,
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
      {
        name: "Island",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    hand_size: 0,
    graveyard: ["Lightning Bolt", "Brainstorm", "Ponder", "Force of Will"],
    stack: [],
    phase: "main",
    turn_number: 8,
  },
  expectedBehaviors: [
    "Complex combat should resolve damage correctly",
    "Multiple stack items should resolve in order",
    "Commander damage should accumulate",
    "Land count should match turn constraints",
    "Board wipe should clear creature types only",
    "Mana availability should match untapped lands",
    "Proliferate should increment all counter types",
  ],
};

describe("Video-Derived Fixture: topdeck-mode", () => {
  it("loads game state successfully", () => {
    expect(typeof topdeck_mode.gameState).toBe("object");
    expect(topdeck_mode.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(topdeck_mode.gameState.player_life)).toBe(true);
    expect(Number.isInteger(topdeck_mode.gameState.opponent_life)).toBe(true);
    expect(Array.isArray(topdeck_mode.gameState.battlefield_player)).toBe(true);
    expect(Array.isArray(topdeck_mode.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof topdeck_mode.gameState.turn_number).toBe("number");
    expect(Number.isInteger(topdeck_mode.gameState.turn_number)).toBe(true);
    expect(topdeck_mode.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof topdeck_mode.gameState.phase).toBe("string");
    expect(topdeck_mode.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(topdeck_mode.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(topdeck_mode.gameState);
  });

  for (const behavior of topdeck_mode.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, topdeck_mode.gameState);
    });
  }
});
