/**
 * Video-Derived Fixture: two-lands-tap-one
 * Description: Two lands with one tapped
 * Fixture ID: two-lands-tap-one
 * Source: video-derived (issue #1397 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/regen-video-fixtures.mjs (issue #1397).
 * Each "validates behavior" it-block now delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const two_lands_tap_one = {
  id: "two-lands-tap-one",
  name: "two-lands-tap-one",
  description: "Two lands with one tapped",
  gameState: {
    player_life: 20,
    opponent_life: 20,
    battlefield_player: [
      {
        name: "Island",
        is_tapped: true,
        power: 0,
        toughness: 0,
      },
      {
        name: "Forest",
        is_tapped: false,
        power: 0,
        toughness: 0,
      },
    ],
    battlefield_opponent: [],
    hand_size: 5,
    graveyard: [],
    stack: [],
    phase: "main",
    turn_number: 2,
  },
  expectedBehaviors: [
    "Game state should serialize without errors",
    "Player life totals should be valid integers",
    "Battlefield arrays should contain valid card entries",
    "Hand size should be a non-negative integer",
    "Phase should be a recognized game phase string",
    "Turn number should be a positive integer",
    "Graveyard should contain card name strings",
    "Stack should contain spell name strings or be empty",
  ],
};

describe("Video-Derived Fixture: two-lands-tap-one", () => {
  it("loads game state successfully", () => {
    expect(typeof two_lands_tap_one.gameState).toBe("object");
    expect(two_lands_tap_one.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(two_lands_tap_one.gameState.player_life)).toBe(
      true,
    );
    expect(Number.isInteger(two_lands_tap_one.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(two_lands_tap_one.gameState.battlefield_player)).toBe(
      true,
    );
    expect(
      Array.isArray(two_lands_tap_one.gameState.battlefield_opponent),
    ).toBe(true);
  });

  it("has valid turn structure", () => {
    expect(typeof two_lands_tap_one.gameState.turn_number).toBe("number");
    expect(Number.isInteger(two_lands_tap_one.gameState.turn_number)).toBe(
      true,
    );
    expect(two_lands_tap_one.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof two_lands_tap_one.gameState.phase).toBe("string");
    expect(two_lands_tap_one.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(two_lands_tap_one.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(two_lands_tap_one.gameState);
  });

  for (const behavior of two_lands_tap_one.expectedBehaviors) {
    it(`validates behavior: ${behavior}`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, two_lands_tap_one.gameState);
    });
  }
});
