// Auto-generated test file from game state fixtures
// Generated by: src/test-utils/generate-test-fixture.ts
// Fixture count: 12

import { describe, it, expect } from '@jest/globals';
import {
  createInitialGameState,
  startGame,
  passPriority,
  dealDamageToPlayer,
  gainLife,
} from '@/lib/game-state/game-state';
import { Phase } from '@/lib/game-state/types';

function playerCount(state: ReturnType<typeof createInitialGameState>): number {
  return state.players.size;
}

function getPlayer(state: ReturnType<typeof createInitialGameState>, idx: number) {
  const ids = Array.from(state.players.keys());
  return state.players.get(ids[idx]);
}

function getManaPool(state: ReturnType<typeof createInitialGameState>, idx: number) {
  const ids = Array.from(state.players.keys());
  return state.players.get(ids[idx])?.manaPool;
}

function getCommanderDamage(state: ReturnType<typeof createInitialGameState>, targetIdx: number, sourceIdx: number) {
  const ids = Array.from(state.players.keys());
  const target = state.players.get(ids[targetIdx]);
  return target?.commanderDamage.get(ids[sourceIdx]);
}
describe('GameFlow fixtures', () => {
  it('Game state after advancing through draw phase', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, false);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);
    while (state.turn.currentPhase !== Phase.DRAW) { state = passPriority(state, state.priorityPlayerId!); }

    expect(state.status).toBe("in_progress");
    expect(state.turn.turnNumber).toBe(1);
    expect(state.turn.currentPhase).toBe("draw");
    expect(state.turn.isFirstTurn).toBe(true);
  });

  it('Game state after startGame is called', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, false);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);

    expect(state.status).toBe("in_progress");
    expect(state.turn.turnNumber).toBe(1);
    expect(state.turn.isFirstTurn).toBe(true);
    expect(state.priorityPlayerId).toBeDefined();
    expect(state.consecutivePasses).toBe(0);
  });

  it('Game state tracking lands played per turn', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, false);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);
    const _lp1 = state.players.get(playerIds[0]); if (_lp1) { _lp1.landsPlayedThisTurn = 1; }

    expect(state.status).toBe("in_progress");
    expect(getPlayer(state, 0).landsPlayedThisTurn).toBe(1);
    expect(getPlayer(state, 0).maxLandsPerTurn).toBe(1);
    expect(getPlayer(state, 1).landsPlayedThisTurn).toBe(0);
  });

  it('Game state after multiple priority passes', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, false);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);
    state = passPriority(state, state.priorityPlayerId!);
      state = passPriority(state, state.priorityPlayerId!);
      state = passPriority(state, state.priorityPlayerId!);

    expect(state.status).toBe("in_progress");
    expect(state.consecutivePasses).toBeGreaterThan(0);
    expect(state.priorityPlayerId).toBeDefined();
  });

});

describe('Combat fixtures', () => {
  it('Game state during combat with declared attackers', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, false);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);
    while (state.turn.currentPhase !== Phase.DECLARE_ATTACKERS) { state = passPriority(state, state.priorityPlayerId!); }
    state.combat.inCombatPhase = true;
      const attackerId = Array.from(state.cards.keys())[0];
      if (attackerId) {
        state.combat.attackers = [{ cardId: attackerId, defenderId: playerIds[1], isAttackingPlaneswalker: false, damageToDeal: 2, hasFirstStrike: false, hasDoubleStrike: false }];
      }

    expect(state.status).toBe("in_progress");
    expect(state.combat.inCombatPhase).toBe(true);
    expect(state.turn.currentPhase).toBe("declare_attackers");
    expect(state.combat.remainingCombatPhases).toBe(0);
  });

});

describe('LifeAndDamage fixtures', () => {
  it('Game state with commander damage tracking', () => {
    let state = createInitialGameState(["Alice","Bob"], 40, true);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);
    const _cmd1 = state.players.get(playerIds[0]); if (_cmd1) { _cmd1.commanderDamage.set(playerIds[1], 7); }
    const _cmd2 = state.players.get(playerIds[1]); if (_cmd2) { _cmd2.commanderDamage.set(playerIds[0], 12); }

    expect(state.status).toBe("in_progress");
    expect(getPlayer(state, 0).life).toBe(40);
    expect(getPlayer(state, 1).life).toBe(40);
    expect(getPlayer(state, 0).hasLost).toBe(false);
    expect(getPlayer(state, 1).hasLost).toBe(false);
  });

  it('Game state after dealing damage and gaining life', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, false);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);
    state = dealDamageToPlayer(state, playerIds[0], 5);
    state = gainLife(state, playerIds[0], 3);

    expect(state.status).toBe("in_progress");
    expect(getPlayer(state, 0).life).toBe(18);
    expect(getPlayer(state, 1).life).toBe(20);
  });

  it('Game state with poison counters on a player', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, false);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);
    const _p1 = state.players.get(playerIds[0]); if (_p1) { _p1.poisonCounters = 8; }

    expect(state.status).toBe("in_progress");
    expect(getPlayer(state, 0).poisonCounters).toBe(8);
    expect(getPlayer(state, 1).poisonCounters).toBe(0);
    expect(getPlayer(state, 0).hasLost).toBe(false);
    expect(getPlayer(state, 1).hasLost).toBe(false);
  });

});

describe('Initialization fixtures', () => {
  it('Fresh 2-player commander game', () => {
    let state = createInitialGameState(["Alice","Bob"], 40, true);
    const playerIds = Array.from(state.players.keys());

    expect(playerCount(state)).toBe(2);
    expect(state.format).toBe("standard");
    expect(state.status).toBe("not_started");
    expect(getPlayer(state, 0).life).toBe(40);
    expect(getPlayer(state, 1).life).toBe(40);
    expect(getPlayer(state, 0).poisonCounters).toBe(0);
    expect(getPlayer(state, 1).poisonCounters).toBe(0);
  });

  it('Fresh 2-player standard game before starting', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, false);
    const playerIds = Array.from(state.players.keys());

    expect(playerCount(state)).toBe(2);
    expect(state.status).toBe("not_started");
    expect(state.turn.turnNumber).toBe(1);
    expect(state.stack.length).toBe(0);
    expect(state.combat.inCombatPhase).toBe(false);
    expect(state.cards.size).toBe(0);
    expect(state.winners.length).toBe(0);
    expect(state.format).toBe("standard");
  });

});

describe('Mana fixtures', () => {
  it('Game state after tapping lands and spending mana', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, false);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);
    const _mp1 = state.players.get(playerIds[0]); if (_mp1) { _mp1.manaPool.white = 3; }
    const _mp2 = state.players.get(playerIds[0]); if (_mp2) { _mp2.manaPool.red = 2; }
    const _mp3 = state.players.get(playerIds[0]); if (_mp3) { _mp3.manaPool.colorless = 1; }

    expect(state.status).toBe("in_progress");
    expect(getManaPool(state, 0).white).toBe(3);
    expect(getManaPool(state, 0).red).toBe(2);
    expect(getManaPool(state, 0).colorless).toBe(1);
    expect(getManaPool(state, 0).blue).toBe(0);
    expect(getManaPool(state, 0).black).toBe(0);
    expect(getManaPool(state, 0).green).toBe(0);
  });

});

describe('Serialization fixtures', () => {
  it('Verify state survives JSON serialization round-trip with Maps', () => {
    let state = createInitialGameState(["Alice","Bob"], 20, true);
    const playerIds = Array.from(state.players.keys());

    state = startGame(state);
    const _cmd1 = state.players.get(playerIds[0]); if (_cmd1) { _cmd1.commanderDamage.set(playerIds[1], 5); }
    const _mp2 = state.players.get(playerIds[1]); if (_mp2) { _mp2.manaPool.white = 2; }

    expect(getPlayer(state, 0).life).toBe(20);
    expect(getPlayer(state, 1).life).toBe(20);
    expect(getManaPool(state, 1).white).toBe(2);
    expect(state.zones.size).toBeGreaterThan(0);
  });

});
