/**
 * Regenerates src/lib/card-scripts/cards/index.generated.ts from the JSON card
 * scripts in that folder. Run after adding or removing a script:
 *
 *   npx tsx scripts/build-card-script-index.ts          # write
 *   npx tsx scripts/build-card-script-index.ts --check  # CI: fail if stale
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = join(__dirname, "..", "src", "lib", "card-scripts", "cards");
const OUT = join(DIR, "index.generated.ts");

const files = readdirSync(DIR)
  .filter((f) => f.endsWith(".json"))
  .sort();

const ident = (f: string) => "s_" + f.replace(/\.json$/, "").replace(/[^a-z0-9_]/gi, "_");

const body = [
  "// Generated by scripts/build-card-script-index.ts. Do not edit by hand.",
  ...files.map((f) => `import ${ident(f)} from "./${f}";`),
  "",
  "export const RAW_CARD_SCRIPTS: unknown[] = [",
  ...files.map((f) => `  ${ident(f)},`),
  "];",
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current !== body) {
    console.error("card script index is stale; run scripts/build-card-script-index.ts");
    process.exit(1);
  }
  console.log(`card script index up to date (${files.length} scripts)`);
} else {
  writeFileSync(OUT, body);
  console.log(`wrote ${files.length} scripts to ${OUT}`);
}
