/**
 * Regenerates src/lib/game-state/card-scripts/cards/index.generated.ts from the JSON card
 * scripts in that folder. Run after adding or removing a script:
 *
 *   npx tsx scripts/build-card-script-index.ts          # write
 *   npx tsx scripts/build-card-script-index.ts --check  # CI: fail if stale
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = join(__dirname, "..", "src", "lib", "game-state", "card-scripts", "cards");
const OUT = join(DIR, "index.generated.ts");

const files = readdirSync(DIR)
  .filter((f) => f.endsWith(".json"))
  .sort();

const ident = (f: string) => "s_" + f.replace(/\.json$/, "").replace(/[^a-z0-9_]/gi, "_");

// The scripts are inlined without their `oracle` field: oracle text is only
// for review and drift checks, and the engine ships in the game page's client
// bundle, where those strings cost ~7 kB (#1814). The JSON files stay the
// source of truth and are validated against CardScriptSchema by the tests.
const runtimeScript = (f: string): string => {
  const { oracle: _oracle, ...rest } = JSON.parse(readFileSync(join(DIR, f), "utf8"));
  return JSON.stringify(rest);
};

const body = [
  "// Generated by scripts/build-card-script-index.ts. Do not edit by hand.",
  "// Card scripts without their oracle text (see the generator for why).",
  "/* prettier-ignore */",
  "export const RAW_CARD_SCRIPTS: unknown[] = [",
  ...files.map((f) => `  ${runtimeScript(f)},`),
  "];",
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current !== body) {
    console.error("card script index is stale; run scripts/build-card-script-index.ts");
    process.exit(1);
  }
  console.info(`card script index up to date (${files.length} scripts)`);
} else {
  writeFileSync(OUT, body);
  console.info(`wrote ${files.length} scripts to ${OUT}`);
}
