#!/usr/bin/env tsx
/**
 * Generate Jest Test Fixtures from Video-Derived Game States
 *
 * This script processes video-derived game state JSON files and generates
 * corresponding Jest test files for automated validation.
 *
 * Issue #1801: The emitted test files use the validateBehavior() helper
 * (see src/lib/game-state/__tests__/video-derived/_helpers/) so every
 * "validates behavior" assertion is a real typed check against the
 * RecognizedBoardState. Tests emitted by this script pass the
 * VIDEO_FIXTURE_STUB guard (issue #1397): no `TODO: Implement validation`
 * placeholders, no `expect(...gameState).toBeDefined()` no-ops.
 *
 * Generated files are skipped when an existing test file of the same name
 * already exists — the script is non-destructive on the original 50
 * fixtures regenerated by scripts/regen-video-fixtures.mjs (issue #1397)
 * and only writes tests for fixtures that lack one (issue #1801:
 * post-v1.6 engine scenarios).
 *
 * Usage:
 *   npx tsx scripts/generate-test-fixture.ts --fixtures-dir path/to/fixtures
 */

import * as fs from "fs";
import * as path from "path";

interface TestFixture {
  id: string;
  name: string;
  description?: string;
  gameState: any;
  expectedBehaviors?: string[];
}

interface TestGenerationOptions {
  fixturesDir: string;
  outputDir: string;
  dryRun?: boolean;
  /**
   * When true (default), skip writing a test file if one already exists
   * for the fixture id. Set `--overwrite` to force regeneration.
   */
  overwrite?: boolean;
}

const DEFAULT_OPTIONS: TestGenerationOptions = {
  fixturesDir: "src/lib/__fixtures__/video-derived",
  outputDir: "src/lib/game-state/__tests__/video-derived",
  dryRun: false,
  overwrite: false,
};

/**
 * Parse command line arguments
 */
function parseArgs(): TestGenerationOptions {
  const args = process.argv.slice(2);
  const options = { ...DEFAULT_OPTIONS };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    const nextArg = args[i + 1];

    if (arg === "--fixtures-dir" && nextArg) {
      options.fixturesDir = nextArg;
      i++;
    } else if (arg === "--output-dir" && nextArg) {
      options.outputDir = nextArg;
      i++;
    } else if (arg === "--dry-run") {
      options.dryRun = true;
    } else if (arg === "--overwrite") {
      options.overwrite = true;
    } else if (arg === "--help") {
      console.log(`
Usage: npx tsx scripts/generate-test-fixture.ts [options]

Options:
  --fixtures-dir <path>   Directory containing video-derived fixture JSON files (default: src/lib/__fixtures__/video-derived)
  --output-dir <path>     Directory to write generated test files (default: src/lib/game-state/__tests__/video-derived)
  --dry-run               Generate tests without writing files
  --overwrite             Overwrite existing test files (default: skip)
  --help                  Show this help message

Example:
  npx tsx scripts/generate-test-fixture.ts --fixtures-dir src/lib/__fixtures__/video-derived
      `);
      process.exit(0);
    }
  }

  return options;
}

/**
 * Load all fixture JSON files from a directory
 */
function loadFixtures(fixturesDir: string): TestFixture[] {
  const fixtures: TestFixture[] = [];

  if (!fs.existsSync(fixturesDir)) {
    console.warn(`Fixtures directory does not exist: ${fixturesDir}`);
    return fixtures;
  }

  const files = fs.readdirSync(fixturesDir);

  for (const file of files) {
    if (!file.endsWith(".json")) continue;

    const filePath = path.join(fixturesDir, file);
    try {
      const content = fs.readFileSync(filePath, "utf-8");
      const data = JSON.parse(content);

      // Normalize fixture data
      const fixture: TestFixture = {
        id: data.id || path.basename(file, ".json"),
        name: data.name || `Video-derived fixture from ${file}`,
        description: data.description,
        gameState: data.gameState || data,
        expectedBehaviors: data.expectedBehaviors || [],
      };

      fixtures.push(fixture);
      console.log(`Loaded fixture: ${fixture.id}`);
    } catch (error) {
      console.error(`Error loading fixture ${file}:`, error);
    }
  }

  return fixtures;
}

/**
 * Generate Jest test file content from a fixture
 *
 * Emits the validateBehavior-based format used by every regenerated test in
 * this directory (issue #1397): four structural smoke tests with real typed
 * assertions, then a loop over `expectedBehaviors` that calls
 * `validateBehavior(behavior, fixture.gameState)`. No `TODO: Implement
 * validation` placeholders, no `expect(...gameState).toBeDefined()` no-ops —
 * the VIDEO_FIXTURE_STUB guard (`__guard__.test.ts`) would fail CI on
 * either pattern.
 *
 * The literal id is `kebab→snake_case` to match the convention used by
 * scripts/regen-video-fixtures.mjs.
 */
function generateTestFile(fixture: TestFixture): string {
  const { id, name, description, expectedBehaviors } = fixture;
  const fixtureId = id.replace(/-/g, "_");
  const descriptionLine = description ? ` * Description: ${description}\n` : "";
  const escapedGameState = JSON.stringify(fixture.gameState, null, 2);
  const escapedBehaviors = JSON.stringify(expectedBehaviors ?? [], null, 2);

  return `/**
 * Video-Derived Fixture: ${id}
${descriptionLine} * Fixture ID: ${id}
 * Source: video-derived (issue #1801 — see docs/TEST_VIDEO_FIXTURES.md)
 *
 * Auto-generated by scripts/generate-test-fixture.ts (issue #1801).
 * Each "validates behavior" it-block delegates to validateBehavior()
 * for a typed assertion against the RecognizedBoardState.
 */

import { validateBehavior } from "./_helpers";

const ${fixtureId} = {
  id: "${id}",
  name: "${name}",
  ${description ? `description: ${JSON.stringify(description)},` : ""}
  gameState: ${escapedGameState},
  expectedBehaviors: ${escapedBehaviors},
};

describe("Video-Derived Fixture: ${id}", () => {
  it("loads game state successfully", () => {
    expect(typeof ${fixtureId}.gameState).toBe("object");
    expect(${fixtureId}.gameState).not.toBeNull();
  });

  it("has valid player data", () => {
    expect(Number.isInteger(${fixtureId}.gameState.player_life)).toBe(true);
    expect(Number.isInteger(${fixtureId}.gameState.opponent_life)).toBe(
      true,
    );
    expect(Array.isArray(${fixtureId}.gameState.battlefield_player)).toBe(
      true,
    );
    expect(Array.isArray(${fixtureId}.gameState.battlefield_opponent)).toBe(
      true,
    );
  });

  it("has valid turn structure", () => {
    expect(typeof ${fixtureId}.gameState.turn_number).toBe("number");
    expect(Number.isInteger(${fixtureId}.gameState.turn_number)).toBe(true);
    expect(${fixtureId}.gameState.turn_number).toBeGreaterThan(0);
    expect(typeof ${fixtureId}.gameState.phase).toBe("string");
    expect(${fixtureId}.gameState.phase.length).toBeGreaterThan(0);
  });

  it("can be serialized and deserialized", () => {
    const serialized = JSON.stringify(${fixtureId}.gameState);
    const deserialized = JSON.parse(serialized);
    expect(deserialized).toEqual(${fixtureId}.gameState);
  });

  for (const behavior of ${fixtureId}.expectedBehaviors) {
    it(\`validates behavior: \${behavior}\`, () => {
      // Real assertion: see _helpers/validate-fixture.ts for the
      // behaviour-string → typed-property mapping. Issue #1397 replaces
      // the previous TODO placeholder with a concrete property check.
      validateBehavior(behavior, ${fixtureId}.gameState);
    });
  }
});
`;
}

/**
 * Write a test file to disk. Skips when a test file already exists for the
 * fixture id unless `--overwrite` is passed — the script's job on the
 * post-v1.6 sweep (issue #1801) is to fill gaps, not to rewrite the 50
 * tests that scripts/regen-video-fixtures.mjs already owns.
 */
function writeTestFile(
  outputDir: string,
  fixture: TestFixture,
  overwrite: boolean,
): "written" | "skipped" {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const fileName = `${fixture.id}.test.ts`;
  const filePath = path.join(outputDir, fileName);

  if (!overwrite && fs.existsSync(filePath)) {
    return "skipped";
  }

  const content = generateTestFile(fixture);
  fs.writeFileSync(filePath, content, "utf-8");
  return "written";
}

/**
 * Main execution
 */
function main(): void {
  const options = parseArgs();

  console.log("=== Video-Derived Test Fixture Generator ===");
  console.log(`Fixtures directory: ${options.fixturesDir}`);
  console.log(`Output directory: ${options.outputDir}`);
  console.log(`Dry run: ${options.dryRun}`);
  console.log(`Overwrite existing: ${options.overwrite}`);
  console.log();

  const fixtures = loadFixtures(options.fixturesDir);

  if (fixtures.length === 0) {
    console.log("No fixtures found. Exiting.");
    return;
  }

  console.log(`\nFound ${fixtures.length} fixtures.\n`);

  if (options.dryRun) {
    for (const fixture of fixtures) {
      const filePath = path.join(options.outputDir, `${fixture.id}.test.ts`);
      const status = fs.existsSync(filePath) ? "skipped" : "would-generate";
      console.log(`  [${status}] ${filePath}`);
    }
    return;
  }

  let written = 0;
  let skipped = 0;
  for (const fixture of fixtures) {
    try {
      const result = writeTestFile(
        options.outputDir,
        fixture,
        !!options.overwrite,
      );
      const filePath = path.join(options.outputDir, `${fixture.id}.test.ts`);
      if (result === "written") {
        console.log(`  ✓ wrote   ${filePath}`);
        written++;
      } else {
        console.log(`  · skipped ${filePath}`);
        skipped++;
      }
    } catch (error) {
      console.error(`Error generating test for ${fixture.id}:`, error);
    }
  }

  console.log(
    `\n✓ Done. ${written} written, ${skipped} skipped (already existed).`,
  );
  console.log(`\nTo run the tests:`);
  console.log(`  npm test -- --testPathPattern=video-derived`);
}

main();

export { parseArgs, loadFixtures, generateTestFile, writeTestFile };
