#!/usr/bin/env bash
# scripts/stamp-tauri-version.sh
#
# Rewrite src-tauri/tauri.conf.json and src-tauri/Cargo.toml so the bundled
# app's version matches the pushed release tag (issue #1588).
#
# Without this, the Tauri 2 updater cannot compare versions because the
# installer binary always reports the hardcoded "1.0.0" placeholder.
#
# Behaviour:
#   - Tag push (refs/tags/vX.Y.Z):  rewrite both files to X.Y.Z
#   - Release publish:              rewrite both files to tag_name (stripped)
#   - workflow_dispatch w/o tag:    NO-OP (build keeps the 1.0.0 placeholder
#                                   so fork PRs and contributor dry-runs
#                                   still work)
#
# The script writes the pre-stamp versions to a small env file so the
# companion scripts/restore-tauri-version.sh can revert after `tauri build`.
# The state file path comes from $STAMP_STATE (defaults to a file under
# $RUNNER_TEMP so it is automatically cleaned between jobs).
#
# Usage:
#   bash scripts/stamp-tauri-version.sh    # uses default paths
#
# Required tools: jq, sed, awk, mktemp (all standard on GitHub-hosted
# runners: windows-latest, macos-latest, ubuntu-22.04).

set -euo pipefail

# -- Inputs (env vars with sensible defaults) -----------------------------
CONF_PATH="${CONF_PATH:-src-tauri/tauri.conf.json}"
CARGO_PATH="${CARGO_PATH:-src-tauri/Cargo.toml}"
# Prefer RUNNER_TEMP so the file is auto-cleaned between jobs; fall back
# to $TMPDIR, then /tmp for local dry-runs.
STATE_FILE="${STAMP_STATE:-${RUNNER_TEMP:-${TMPDIR:-/tmp}}/tauri-version-stamp.env}"

# Tag or release tag_name passed in by the calling workflow step. The
# caller is responsible for stripping a leading "refs/tags/" — we only
# strip the leading "v" here. May be empty for workflow_dispatch.
RAW_VERSION="${RELEASE_VERSION_RAW:-}"

# Fall back to GITHUB_REF (set by every GitHub Actions run). For tag
# pushes GITHUB_REF is "refs/tags/vX.Y.Z"; for release events it points
# at the default branch, which is why the caller may also pass
# RELEASE_VERSION_RAW directly.
if [[ -z "$RAW_VERSION" && -n "${GITHUB_REF:-}" && "${GITHUB_REF}" == refs/tags/* ]]; then
  RAW_VERSION="${GITHUB_REF#refs/tags/}"
fi

# Strip the leading "v" so "v1.8.0" -> "1.8.0" (Tauri and Cargo both
# reject a leading "v" in semver).
VERSION="${RAW_VERSION#v}"

# -- No-op when no release tag is present --------------------------------
#
# workflow_dispatch runs without a tag must still build with the
# hardcoded 1.0.0 placeholder so contributor dry-runs and fork PRs keep
# working.
if [[ -z "$VERSION" ]]; then
  mkdir -p "$(dirname "$STATE_FILE")"
  {
    echo "# Auto-generated by scripts/stamp-tauri-version.sh (issue #1588)."
    echo "STAMPED=false"
  } > "$STATE_FILE"
  echo "[stamp-tauri-version] No release tag detected — leaving hardcoded 1.0.0 in place."
  exit 0
fi

# -- Validate the derived version is plausible semver --------------------
#
# Tauri and Cargo both reject invalid semver; failing here with a
# ::error:: annotation points the maintainer at the stamp step instead
# of leaving a confusing cargo/tauri error deep in the build log.
SEMVER_REGEX='^[0-9]+(\.[0-9]+){1,2}([-+][0-9A-Za-z.-]+)?$'
if ! [[ "$VERSION" =~ $SEMVER_REGEX ]]; then
  echo "::error::Derived version '$VERSION' is not a valid semver string. Refusing to stamp tauri.conf.json/Cargo.toml." >&2
  exit 1
fi

if [[ ! -f "$CONF_PATH" ]]; then
  echo "::error::tauri.conf.json not found at $CONF_PATH" >&2
  exit 1
fi
if [[ ! -f "$CARGO_PATH" ]]; then
  echo "::error::Cargo.toml not found at $CARGO_PATH" >&2
  exit 1
fi
for tool in jq sed awk; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "::error::Required tool '$tool' is not on PATH" >&2
    exit 1
  fi
done

# -- Snapshot the original values ----------------------------------------
ORIG_CONF_VERSION=$(jq -r '.version' "$CONF_PATH")
# Tauri Cargo.toml currently has only one version line near the top of
# the [package] block; anchoring on the line shape keeps the extraction
# robust if more version fields are added later.
ORIG_CARGO_VERSION=$(awk -F'"' '/^version[[:space:]]*=/{print $2; exit}' "$CARGO_PATH")
if [[ -z "$ORIG_CONF_VERSION" || "$ORIG_CONF_VERSION" == "null" ]]; then
  echo "::error::Could not read .version from $CONF_PATH" >&2
  exit 1
fi
if [[ -z "$ORIG_CARGO_VERSION" ]]; then
  echo "::error::Could not read [package] version from $CARGO_PATH" >&2
  exit 1
fi
echo "[stamp-tauri-version] Stamping $CONF_PATH and $CARGO_PATH:" \
  "$ORIG_CONF_VERSION / $ORIG_CARGO_VERSION -> $VERSION"

# -- Rewrite tauri.conf.json via jq --------------------------------------
tmp=$(mktemp)
# shellcheck disable=SC2064
trap "rm -f '$tmp'" EXIT
jq --arg v "$VERSION" '.version = $v' "$CONF_PATH" > "$tmp"
mv "$tmp" "$CONF_PATH"

# -- Rewrite Cargo.toml via sed ------------------------------------------
#
# GNU sed is preinstalled on every GitHub-hosted runner image
# (windows-latest, macos-latest, ubuntu-22.04). The match anchors on the
# exact previous version string so we don't accidentally rewrite a
# future-added dependency's version line.
ESCAPED_ORIG=${ORIG_CARGO_VERSION//\//\\/}
ESCAPED_NEW=${VERSION//\//\\/}
sed -i.bak "s|^version = \"${ESCAPED_ORIG}\"|version = \"${ESCAPED_NEW}\"|" "$CARGO_PATH"
rm -f "${CARGO_PATH}.bak"

# -- Verify the rewrites parse cleanly -----------------------------------
#
# Catches stamp mistakes (jq dropped a trailing newline, sed mangled a
# quoting edge case) before the much-more-expensive `tauri build` runs.
if ! jq -e --arg v "$VERSION" '.version == $v' "$CONF_PATH" >/dev/null; then
  echo "::error::Stamp verification failed: $CONF_PATH does not contain version $VERSION" >&2
  exit 1
fi
if ! grep -F "version = \"$VERSION\"" "$CARGO_PATH" >/dev/null; then
  echo "::error::Stamp verification failed: $CARGO_PATH does not contain version $VERSION" >&2
  exit 1
fi

# -- Write state file for the restore step -------------------------------
mkdir -p "$(dirname "$STATE_FILE")"
{
  echo "# Auto-generated by scripts/stamp-tauri-version.sh (issue #1588)."
  echo "# Consumed by scripts/restore-tauri-version.sh."
  echo "STAMPED=true"
  echo "ORIG_CONF_VERSION=$ORIG_CONF_VERSION"
  echo "ORIG_CARGO_VERSION=$ORIG_CARGO_VERSION"
  echo "NEW_VERSION=$VERSION"
} > "$STATE_FILE"

echo "[stamp-tauri-version] Stamped to $VERSION (state at $STATE_FILE)"
