/**
 * @fileOverview IndexedDB Schema Migration Tests — v3 → v4 (issue #1811)
 *
 * Validates that opening `PlanarNexusStorage` at v4 from a state where
 * the four "not blessed" standalone single-store databases
 * (`PlanarNexusGameDB`, `PlanarNexusSearchDB`, `PlanarNexusPresetsDB`,
 * `PlanarNexusRecentSearchesDB`) still hold legacy data:
 *   1. Every legacy row ends up readable via `indexedDBStorage.get()` on
 *      the new consolidated stores (no silent data loss).
 *   2. A row written to a new store BEFORE the upgrade survives the
 *      upgrade untouched (round-trip; pre-existing v4 rows are not
 *      overwritten by empty legacy data).
 *   3. The legacy standalone DBs are empty after upgrade — data moved,
 *      not duplicated — and the legacy DBs themselves are deleted.
 *   4. Re-running the consolidation (close + reopen) is a no-op.
 *
 * The v3 fixtures are hand-written here (not generated by the v3 code
 * path) so the test would still catch regressions if a future developer
 * accidentally deletes the lazy create-on-upgrade branch in
 * `initialize()` or the v3 → v4 consolidation handler. Mirrors the
 * pattern in `indexeddb-migration-v3-split.test.ts`.
 */

import "fake-indexeddb/auto";
import {
  describe,
  it,
  expect,
  beforeEach,
  afterEach,
  jest,
} from "@jest/globals";
import {
  IndexedDBStorage,
  LOCAL_GAME_CODES_STORE,
  LOCAL_GAME_STATE_STORE,
  RECENT_SEARCHES_STORE,
  SEARCH_PREFERENCES_STORE,
  SEARCH_PRESETS_STORE,
  type StorageConfig,
} from "../indexeddb-storage";

const DB_NAME = "TestPlanarNexusMigrationV4";

/**
 * The v3-era store list as published by the production code prior to
 * issue #1811. Keeps the v3→v4 upgrade on this list (the legacy DBs
 * are *external*, not part of PlanarNexusStorage v3).
 */
const V3_CONFIG_STORES = [
  "decks",
  "saved-games",
  "saved-games-meta",
  "saved-games-payloads",
  "preferences",
  "usage-tracking",
  "achievements",
  "game-history",
] as const;

const V4_CONFIG: StorageConfig = {
  dbName: DB_NAME,
  version: 4,
  stores: [
    ...V3_CONFIG_STORES,
    LOCAL_GAME_STATE_STORE,
    LOCAL_GAME_CODES_STORE,
    SEARCH_PREFERENCES_STORE,
    SEARCH_PRESETS_STORE,
    RECENT_SEARCHES_STORE,
  ],
};

/**
 * Seed a representative fixture into each of the four legacy standalone
 * databases. Returns once every write is durable.
 */
async function seedLegacyDatabases(): Promise<void> {
  const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
    .indexedDB;

  // PlanarNexusGameDB v1 — games store (keyPath `gameId`) + gameCodes
  // store (keyPath `gameCode`).
  await new Promise<void>((resolve, reject) => {
    const req = idb.open("PlanarNexusGameDB", 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      const games = db.createObjectStore("games", { keyPath: "gameId" });
      games.createIndex("gameCode", "gameCode", { unique: true });
      games.createIndex("status", "status", { unique: false });
      games.createIndex("updatedAt", "updatedAt", { unique: false });
      db.createObjectStore("gameCodes", { keyPath: "gameCode" });
    };
    req.onsuccess = () => {
      const db = req.result;
      const tx = db.transaction(["games", "gameCodes"], "readwrite");
      const games = tx.objectStore("games");
      const codes = tx.objectStore("gameCodes");

      games.put({
        gameId: "game-1",
        gameCode: "CODE-1",
        hostId: "host-1",
        hostName: "Alice",
        gameStateVersion: 1,
        createdAt: 1_700_000_000_000,
        updatedAt: 1_700_000_000_500,
        lastActionAt: 1_700_000_000_500,
        status: "active",
      });
      games.put({
        gameId: "game-2",
        gameCode: "LOCAL-resume-key-2",
        hostId: "host-2",
        hostName: "Bob",
        gameStateVersion: 4,
        createdAt: 1_700_000_001_000,
        updatedAt: 1_700_000_002_000,
        lastActionAt: 1_700_000_002_000,
        status: "paused",
        source: "p2p",
        resumeKey: "resume-key-2",
      });
      codes.put({ gameCode: "CODE-1", gameId: "game-1" });
      codes.put({
        gameCode: "LOCAL-resume-key-2",
        gameId: "game-2",
      });

      tx.oncomplete = () => {
        db.close();
        resolve();
      };
      tx.onerror = () => reject(tx.error ?? new Error("seed GameDB tx failed"));
      tx.onabort = () =>
        reject(tx.error ?? new Error("seed GameDB tx aborted"));
    };
    req.onerror = () => reject(req.error ?? new Error("GameDB v1 open failed"));
  });

  // PlanarNexusSearchDB v1 — preferences store (keyPath `id`).
  await new Promise<void>((resolve, reject) => {
    const req = idb.open("PlanarNexusSearchDB", 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      db.createObjectStore("preferences", { keyPath: "id" });
    };
    req.onsuccess = () => {
      const db = req.result;
      const tx = db.transaction(["preferences"], "readwrite");
      tx.objectStore("preferences").put({
        id: "user-prefs",
        prefs: { sortOption: "cmc", sortDirection: "desc", fuzzyThreshold: 1 },
        updatedAt: 1_700_000_000_000,
      });
      tx.oncomplete = () => {
        db.close();
        resolve();
      };
      tx.onerror = () =>
        reject(tx.error ?? new Error("seed SearchDB tx failed"));
      tx.onabort = () =>
        reject(tx.error ?? new Error("seed SearchDB tx aborted"));
    };
    req.onerror = () =>
      reject(req.error ?? new Error("SearchDB v1 open failed"));
  });

  // PlanarNexusPresetsDB v1 — search-presets store (keyPath `id`,
  // indexes name + updatedAt).
  await new Promise<void>((resolve, reject) => {
    const req = idb.open("PlanarNexusPresetsDB", 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      const store = db.createObjectStore("search-presets", { keyPath: "id" });
      store.createIndex("name", "name", { unique: false });
      store.createIndex("updatedAt", "updatedAt", { unique: false });
    };
    req.onsuccess = () => {
      const db = req.result;
      const tx = db.transaction(["search-presets"], "readwrite");
      const store = tx.objectStore("search-presets");
      store.put({
        id: "preset-1",
        name: "Commander ramp",
        filters: { cmcMin: 0, cmcMax: 3, colors: ["G"] },
        sortOption: "cmc",
        sortDirection: "asc",
        createdAt: 1_700_000_000_000,
        updatedAt: 1_700_000_001_000,
      });
      store.put({
        id: "preset-2",
        name: "Removal-heavy",
        filters: { colors: ["W", "B"] },
        createdAt: 1_700_000_002_000,
        updatedAt: 1_700_000_003_000,
      });
      tx.oncomplete = () => {
        db.close();
        resolve();
      };
      tx.onerror = () =>
        reject(tx.error ?? new Error("seed PresetsDB tx failed"));
      tx.onabort = () =>
        reject(tx.error ?? new Error("seed PresetsDB tx aborted"));
    };
    req.onerror = () =>
      reject(req.error ?? new Error("PresetsDB v1 open failed"));
  });

  // PlanarNexusRecentSearchesDB v1 — recent-searches store (keyPath
  // `query`, index lastUsedAt).
  await new Promise<void>((resolve, reject) => {
    const req = idb.open("PlanarNexusRecentSearchesDB", 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      const store = db.createObjectStore("recent-searches", {
        keyPath: "query",
      });
      store.createIndex("lastUsedAt", "lastUsedAt", { unique: false });
    };
    req.onsuccess = () => {
      const db = req.result;
      const tx = db.transaction(["recent-searches"], "readwrite");
      const store = tx.objectStore("recent-searches");
      store.put({ query: "lightning bolt", lastUsedAt: 1_700_000_003_000 });
      store.put({ query: "ramp", lastUsedAt: 1_700_000_004_000 });
      tx.oncomplete = () => {
        db.close();
        resolve();
      };
      tx.onerror = () =>
        reject(tx.error ?? new Error("seed RecentSearchesDB tx failed"));
      tx.onabort = () =>
        reject(tx.error ?? new Error("seed RecentSearchesDB tx aborted"));
    };
    req.onerror = () =>
      reject(req.error ?? new Error("RecentSearchesDB v1 open failed"));
  });
}

/**
 * Read every row from a legacy standalone DB by opening it at v1 and
 * pulling the store's contents. Used to assert post-upgrade emptiness
 * (acceptance criterion: legacy DBs are empty after upgrade).
 */
async function readAllFromLegacyDb(
  dbName: string,
  storeName: string,
  version: number,
  legacyKeyPath: "gameId" | "gameCode" | "id" | "query",
): Promise<Record<string, unknown>[]> {
  const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
    .indexedDB;
  return new Promise<Record<string, unknown>[]>((resolve, reject) => {
    const req = idb.open(dbName, version);
    req.onupgradeneeded = () => {
      // Re-create the legacy schema so the open succeeds even after
      // the production migration deleted the DB. This is the test's
      // private re-creation, NOT a real legacy DB.
      const db = req.result;
      if (!db.objectStoreNames.contains(storeName)) {
        const store = db.createObjectStore(storeName, {
          keyPath: legacyKeyPath,
        });
        if (storeName === "games") {
          store.createIndex("gameCode", "gameCode", { unique: true });
          store.createIndex("status", "status", { unique: false });
          store.createIndex("updatedAt", "updatedAt", { unique: false });
        } else if (storeName === "search-presets") {
          store.createIndex("name", "name", { unique: false });
          store.createIndex("updatedAt", "updatedAt", { unique: false });
        } else if (storeName === "recent-searches") {
          store.createIndex("lastUsedAt", "lastUsedAt", { unique: false });
        }
      }
    };
    req.onsuccess = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(storeName)) {
        db.close();
        resolve([]);
        return;
      }
      const tx = db.transaction(storeName, "readonly");
      const request = tx.objectStore(storeName).getAll();
      request.onsuccess = () => {
        db.close();
        resolve(request.result || []);
      };
      request.onerror = () => {
        db.close();
        reject(request.error ?? new Error("legacy getAll failed"));
      };
    };
    req.onerror = () => {
      // If the DB does not exist (post-migration delete), this fires.
      // Treat that as "no rows" for the assertion.
      resolve([]);
    };
    req.onblocked = () => resolve([]);
  });
}

/**
 * Drop every test database (PlanarNexusStorage + the four legacy ones).
 * Tolerates "not found".
 */
async function dropDatabase(name: string): Promise<void> {
  const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
    .indexedDB;
  await new Promise<void>((resolve) => {
    const req = idb.deleteDatabase(name);
    req.onsuccess = () => resolve();
    req.onerror = () => resolve();
    req.onblocked = () => resolve();
  });
}

beforeEach(async () => {
  await Promise.all([
    dropDatabase(DB_NAME),
    dropDatabase("PlanarNexusGameDB"),
    dropDatabase("PlanarNexusSearchDB"),
    dropDatabase("PlanarNexusPresetsDB"),
    dropDatabase("PlanarNexusRecentSearchesDB"),
  ]);
});

afterEach(async () => {
  await Promise.all([
    dropDatabase(DB_NAME),
    dropDatabase("PlanarNexusGameDB"),
    dropDatabase("PlanarNexusSearchDB"),
    dropDatabase("PlanarNexusPresetsDB"),
    dropDatabase("PlanarNexusRecentSearchesDB"),
  ]);
  jest.restoreAllMocks();
});

describe("IndexedDB schema migration (v3 to v4, issue #1811 consolidation)", () => {
  it("migrates every legacy row into the new consolidated stores without data loss", async () => {
    await seedLegacyDatabases();

    const storage = new IndexedDBStorage(V4_CONFIG);
    await storage.initialize();

    // local-game-state (PlanarNexusGameDB.games) — every original
    // session lands with the `gameId` mirrored onto the wrapper-class
    // `id` field.
    const games = await storage.getAll<Record<string, unknown>>(
      LOCAL_GAME_STATE_STORE,
    );
    expect(games).toHaveLength(2);
    expect(games.find((g) => g.id === "game-1")?.gameCode).toBe("CODE-1");
    expect(games.find((g) => g.id === "game-2")?.resumeKey).toBe(
      "resume-key-2",
    );

    // local-game-codes (PlanarNexusGameDB.gameCodes) — every mapping
    // row lands keyed by id = gameCode.
    const codes = await storage.getAll<Record<string, unknown>>(
      LOCAL_GAME_CODES_STORE,
    );
    expect(codes).toHaveLength(2);
    expect(codes.find((c) => c.id === "CODE-1")?.gameId).toBe("game-1");
    expect(codes.find((c) => c.id === "LOCAL-resume-key-2")?.gameId).toBe(
      "game-2",
    );

    // search-preferences (PlanarNexusSearchDB.preferences) — the legacy
    // row is preserved verbatim.
    const prefs = await storage.get<Record<string, unknown>>(
      SEARCH_PREFERENCES_STORE,
      "user-prefs",
    );
    expect(prefs).not.toBeNull();
    expect(prefs?.prefs).toEqual({
      sortOption: "cmc",
      sortDirection: "desc",
      fuzzyThreshold: 1,
    });

    // search-presets (PlanarNexusPresetsDB.search-presets) — every
    // preset lands with id preserved.
    const presets =
      await storage.getAll<Record<string, unknown>>(SEARCH_PRESETS_STORE);
    expect(presets).toHaveLength(2);
    expect(presets.find((p) => p.id === "preset-1")?.name).toBe(
      "Commander ramp",
    );

    // recent-searches (PlanarNexusRecentSearchesDB.recent-searches) —
    // every query lands with id = query.
    const recents = await storage.getAll<Record<string, unknown>>(
      RECENT_SEARCHES_STORE,
    );
    expect(recents).toHaveLength(2);
    expect(recents.find((r) => r.id === "lightning bolt")).toBeDefined();
    expect(recents.find((r) => r.id === "ramp")).toBeDefined();

    // The marker row is set so re-opens short-circuit.
    const marker = await storage.get<Record<string, unknown>>(
      "preferences",
      "v4-consolidation-done",
    );
    expect(marker).not.toBeNull();
    expect(marker?.migratedAny).toBe(true);

    await storage.close();
  });

  it("a row written to a new store before upgrade survives the upgrade", async () => {
    // Seed a fresh v4 storage with a pre-existing row in
    // `local-game-state`. The lazy migration must NOT overwrite it with
    // legacy data (none exists here, but the idempotency guard is what
    // protects it when a user partially upgraded).
    const firstStorage = new IndexedDBStorage(V4_CONFIG);
    await firstStorage.initialize();
    await firstStorage.set(LOCAL_GAME_STATE_STORE, {
      id: "user-game",
      gameId: "user-game",
      gameCode: "USER-CODE",
      hostId: "host-user",
      hostName: "User",
      gameStateVersion: 9,
      createdAt: 1_700_000_010_000,
      updatedAt: 1_700_000_011_000,
      lastActionAt: 1_700_000_011_000,
      status: "active",
    });
    await firstStorage.close();

    // Re-open — the marker is set, so no migration runs. The
    // pre-existing row must still be there.
    const secondStorage = new IndexedDBStorage(V4_CONFIG);
    await secondStorage.initialize();
    const row = await secondStorage.get<Record<string, unknown>>(
      LOCAL_GAME_STATE_STORE,
      "user-game",
    );
    expect(row).not.toBeNull();
    expect(row?.gameStateVersion).toBe(9);
    await secondStorage.close();
  });

  it("the legacy standalone databases are emptied after upgrade", async () => {
    await seedLegacyDatabases();

    const storage = new IndexedDBStorage(V4_CONFIG);
    await storage.initialize();
    await storage.close();

    // Each legacy DB's rows must be gone (the migration deleted the
    // DB, so a fresh open at v1 finds nothing).
    const gameRows = await readAllFromLegacyDb(
      "PlanarNexusGameDB",
      "games",
      1,
      "gameId",
    );
    expect(gameRows).toEqual([]);

    const codeRows = await readAllFromLegacyDb(
      "PlanarNexusGameDB",
      "gameCodes",
      1,
      "gameCode",
    );
    expect(codeRows).toEqual([]);

    const prefRows = await readAllFromLegacyDb(
      "PlanarNexusSearchDB",
      "preferences",
      1,
      "id",
    );
    expect(prefRows).toEqual([]);

    const presetRows = await readAllFromLegacyDb(
      "PlanarNexusPresetsDB",
      "search-presets",
      1,
      "id",
    );
    expect(presetRows).toEqual([]);

    const recentRows = await readAllFromLegacyDb(
      "PlanarNexusRecentSearchesDB",
      "recent-searches",
      1,
      "query",
    );
    expect(recentRows).toEqual([]);
  });

  it("re-running the consolidation (close + reopen at v4) is idempotent", async () => {
    await seedLegacyDatabases();

    // First open: run the consolidation.
    const first = new IndexedDBStorage(V4_CONFIG);
    await first.initialize();
    await first.close();

    // Second open: the marker short-circuits the migration; the new
    // stores must still have exactly the seeded rows (no duplicates).
    const second = new IndexedDBStorage(V4_CONFIG);
    await second.initialize();

    const games = await second.getAll(LOCAL_GAME_STATE_STORE);
    expect(games).toHaveLength(2);

    const codes = await second.getAll(LOCAL_GAME_CODES_STORE);
    expect(codes).toHaveLength(2);

    const presets = await second.getAll(SEARCH_PRESETS_STORE);
    expect(presets).toHaveLength(2);

    const recents = await second.getAll(RECENT_SEARCHES_STORE);
    expect(recents).toHaveLength(2);

    await second.close();
  });
});
