/**
 * @fileOverview IndexedDB Schema Migration Tests
 *
 * Issue #1250 (Phase 34: IndexedDB schema audit)
 *
 * Validates that opening the database at v2 from a v1 fixture:
 *   1. Preserves all existing records (no silent data loss).
 *   2. Adds any new indexes introduced in the v1 → v2 delta.
 *   3. Creates all expected object stores from a clean slate.
 *
 * The v1 schema fixture is hand-written here (not generated by the v1
 * code path) so the test would still catch regressions if a future
 * developer accidentally deletes the lazy create-on-upgrade branch
 * in initialize().
 */

import "fake-indexeddb/auto";
import {
  describe,
  it,
  expect,
  beforeEach,
  afterEach,
  jest,
} from "@jest/globals";
import {
  IndexedDBStorage,
  type StorageConfig,
  type StoredDeck,
  type StoredGame,
  type UsageRecord,
  type PlayerAchievements,
} from "../indexeddb-storage";

const DB_NAME = "TestPlanarNexusMigration";

const V1_FIXTURE_STORES = [
  "decks",
  "saved-games",
  "preferences",
  "usage-tracking",
  "achievements",
  "game-history",
] as const;

const V2_CONFIG: StorageConfig = {
  dbName: DB_NAME,
  version: 2,
  stores: [...V1_FIXTURE_STORES],
};

/**
 * Open the database at version 1 with a hand-written schema and seed
 * it with a representative record fixture. Returns once seeding is
 * durable.
 */
async function seedV1Fixture(): Promise<void> {
  // The global indexedDB is fake-indexeddb (auto-imported above).
  const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
    .indexedDB;

  await new Promise<void>((resolve, reject) => {
    const req = idb.open(DB_NAME, 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      // v1 layout — mirrors what the production code lazily creates
      // when it first opens at v1. Keep this in lockstep with the
      // historical schema; do NOT add v2-only fields here.
      const decks = db.createObjectStore("decks", { keyPath: "id" });
      decks.createIndex("name", "name", { unique: false });
      decks.createIndex("format", "format", { unique: false });
      decks.createIndex("createdAt", "createdAt", { unique: false });
      decks.createIndex("updatedAt", "updatedAt", { unique: false });

      const games = db.createObjectStore("saved-games", { keyPath: "id" });
      games.createIndex("name", "name", { unique: false });
      games.createIndex("format", "format", { unique: false });
      games.createIndex("status", "status", { unique: false });
      games.createIndex("savedAt", "savedAt", { unique: false });
      games.createIndex("isAutoSave", "isAutoSave", { unique: false });

      db.createObjectStore("preferences", { keyPath: "id" });

      const usage = db.createObjectStore("usage-tracking", { keyPath: "id" });
      usage.createIndex("provider", "provider", { unique: false });
      usage.createIndex("timestamp", "timestamp", { unique: false });

      db.createObjectStore("achievements", { keyPath: "id" });

      const history = db.createObjectStore("game-history", { keyPath: "id" });
      history.createIndex("date", "date", { unique: false });
      history.createIndex("result", "result", { unique: false });
      history.createIndex("mode", "mode", { unique: false });
    };
    req.onsuccess = () => {
      const db = req.result;
      const tx = db.transaction([...V1_FIXTURE_STORES], "readwrite");
      const stores = {
        decks: tx.objectStore("decks"),
        "saved-games": tx.objectStore("saved-games"),
        preferences: tx.objectStore("preferences"),
        "usage-tracking": tx.objectStore("usage-tracking"),
        achievements: tx.objectStore("achievements"),
        "game-history": tx.objectStore("game-history"),
      };

      // 100 deck records (issue acceptance criterion)
      for (let i = 0; i < 100; i++) {
        const deck: StoredDeck = {
          id: `deck-${i}`,
          name: `Deck ${i}`,
          format: "standard",
          cards: [],
          createdAt: "2025-01-01T00:00:00.000Z",
          updatedAt: "2025-06-01T00:00:00.000Z",
          metadata: { index: i },
        };
        stores.decks.put(deck);
      }

      // 25 saved games
      for (let i = 0; i < 25; i++) {
        const game: StoredGame = {
          id: `game-${i}`,
          name: `Game ${i}`,
          format: "standard",
          playerNames: ["Alice", "Bob"],
          savedAt: 1_700_000_000_000 + i,
          createdAt: 1_700_000_000_000 + i - 1000,
          turnNumber: i,
          currentPhase: "main",
          status: "in_progress",
          isAutoSave: false,
          gameStateJson: "{}",
          metadata: {},
        };
        stores["saved-games"].put(game);
      }

      // 10 preferences (keyPath-only store)
      for (let i = 0; i < 10; i++) {
        stores.preferences.put({ id: `pref-${i}`, value: i });
      }

      // 10 usage records
      for (let i = 0; i < 10; i++) {
        const rec: UsageRecord = {
          id: `usage-${i}`,
          provider: "anthropic",
          timestamp: 1_700_000_000_000 + i,
          tokensUsed: 100 + i,
          inputTokens: 50 + i,
          outputTokens: 50,
          costEstimate: 0.001,
          model: "claude",
        };
        stores["usage-tracking"].put(rec);
      }

      // 5 achievements
      for (let i = 0; i < 5; i++) {
        const ach: PlayerAchievements = {
          id: `ach-${i}`,
          playerId: "player-1",
          achievements: [],
          totalPoints: i * 10,
          lastUpdated: 1_700_000_000_000,
        };
        stores.achievements.put(ach);
      }

      // 30 history records
      for (let i = 0; i < 30; i++) {
        stores["game-history"].put({
          id: `hist-${i}`,
          date: 1_700_000_000_000 + i * 1000,
          result: i % 2 === 0 ? "win" : "loss",
          mode: "vs_ai",
        });
      }

      tx.oncomplete = () => {
        db.close();
        resolve();
      };
      tx.onerror = () => reject(tx.error ?? new Error("seed tx failed"));
      tx.onabort = () => reject(tx.error ?? new Error("seed tx aborted"));
    };
    req.onerror = () => reject(req.error ?? new Error("v1 open failed"));
  });
}

/**
 * Drop the test database. Tolerates "not found" because some tests
 * may run against a fresh environment.
 */
async function dropDatabase(): Promise<void> {
  const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
    .indexedDB;
  await new Promise<void>((resolve) => {
    const req = idb.deleteDatabase(DB_NAME);
    req.onsuccess = () => resolve();
    req.onerror = () => resolve();
    req.onblocked = () => resolve();
  });
}

beforeEach(async () => {
  await dropDatabase();
});

afterEach(async () => {
  await dropDatabase();
  jest.restoreAllMocks();
});

describe("IndexedDB schema migration (v1 → v2)", () => {
  it("opens v2 against a v1 fixture without losing records", async () => {
    // Seed v1 first, then open v2 on top of it.
    await seedV1Fixture();

    const v2Storage = new IndexedDBStorage(V2_CONFIG);
    await v2Storage.initialize();

    // Every record from the v1 fixture must survive the upgrade.
    const decks = await v2Storage.getAll<StoredDeck>("decks");
    expect(decks).toHaveLength(100);
    expect(decks.find((d) => d.id === "deck-0")?.name).toBe("Deck 0");
    expect(decks.find((d) => d.id === "deck-99")?.metadata).toEqual({
      index: 99,
    });

    const games = await v2Storage.getAll<StoredGame>("saved-games");
    expect(games).toHaveLength(25);
    expect(games.find((g) => g.id === "game-12")?.turnNumber).toBe(12);

    const prefs = await v2Storage.getAll<{ id: string; value: number }>(
      "preferences",
    );
    expect(prefs).toHaveLength(10);

    const usage = await v2Storage.getAll<UsageRecord>("usage-tracking");
    expect(usage).toHaveLength(10);

    const ach = await v2Storage.getAll<PlayerAchievements>("achievements");
    expect(ach).toHaveLength(5);

    const history = await v2Storage.getAll("game-history");
    expect(history).toHaveLength(30);

    await v2Storage.close();
  });

  it("preserves v1 indexes after the v1 → v2 upgrade", async () => {
    await seedV1Fixture();

    const v2Storage = new IndexedDBStorage(V2_CONFIG);
    await v2Storage.initialize();

    // Open a raw transaction to introspect the on-disk schema.
    const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
      .indexedDB;
    const db = await new Promise<IDBDatabase>((resolve, reject) => {
      const req = idb.open(DB_NAME, 2);
      req.onsuccess = () => resolve(req.result);
      req.onerror = () => reject(req.error ?? new Error("v2 open failed"));
    });

    try {
      const expectedIndexes: Record<string, string[]> = {
        decks: ["name", "format", "createdAt", "updatedAt"],
        "saved-games": ["name", "format", "status", "savedAt", "isAutoSave"],
        "usage-tracking": ["provider", "timestamp"],
        "game-history": ["date", "result", "mode"],
      };

      for (const [storeName, indexes] of Object.entries(expectedIndexes)) {
        const tx = db.transaction(storeName, "readonly");
        const store = tx.objectStore(storeName);
        const actual = Array.from(store.indexNames).sort();
        expect(actual).toEqual([...indexes].sort());
      }

      // KeyPath-only stores should have no indexes.
      const prefTx = db.transaction("preferences", "readonly");
      expect(Array.from(prefTx.objectStore("preferences").indexNames)).toEqual(
        [],
      );
      const achTx = db.transaction("achievements", "readonly");
      expect(Array.from(achTx.objectStore("achievements").indexNames)).toEqual(
        [],
      );
    } finally {
      db.close();
      await v2Storage.close();
    }
  });

  it("creates every object store from a clean-slate v2 open", async () => {
    // No fixture seeded — database must not exist.
    const storage = new IndexedDBStorage(V2_CONFIG);
    await storage.initialize();

    const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
      .indexedDB;
    const db = await new Promise<IDBDatabase>((resolve, reject) => {
      const req = idb.open(DB_NAME, 2);
      req.onsuccess = () => resolve(req.result);
      req.onerror = () => reject(req.error ?? new Error("v2 open failed"));
    });

    try {
      const names = Array.from(db.objectStoreNames).sort();
      expect(names).toEqual([...V1_FIXTURE_STORES].sort());
      for (const storeName of names) {
        const tx = db.transaction(storeName, "readonly");
        const store = tx.objectStore(storeName);
        expect(store.keyPath).toBe("id");
        // Fresh database is empty.
        expect(
          await new Promise<number>((resolve, reject) => {
            const req = store.count();
            req.onsuccess = () => resolve(req.result);
            req.onerror = () => reject(req.error);
          }),
        ).toBe(0);
      }
    } finally {
      db.close();
      await storage.close();
    }
  });

  it("re-opening at the same version is a no-op (records still readable)", async () => {
    await seedV1Fixture();

    const first = new IndexedDBStorage(V2_CONFIG);
    await first.initialize();
    await first.close();

    const second = new IndexedDBStorage(V2_CONFIG);
    await second.initialize();
    const decks = await second.getAll<StoredDeck>("decks");
    expect(decks).toHaveLength(100);
    await second.close();
  });
});
