/**
 * @fileOverview IndexedDB Schema Migration Tests — v2 → v3 (issue #1572)
 *
 * Validates that opening the database at v3 from a v2 fixture (containing
 * pre-split monolithic `saved-games` rows):
 *   1. Preserves every existing record (no silent data loss).
 *   2. Splits each `saved-games` row into its (meta + payload) pair.
 *   3. Leaves the legacy `saved-games` store empty but intact (so a
 *      downgrade path remains available).
 *   4. Re-running the migration (e.g. open + close + re-open at v3) is
 *      a no-op for the split stores.
 *
 * The v2 schema fixture is hand-written here (not generated by the v2
 * code path) so the test would still catch regressions if a future
 * developer accidentally deletes the lazy create-on-upgrade branch in
 * initialize() or the v2 → v3 split handler.
 */

import "fake-indexeddb/auto";
import {
  describe,
  it,
  expect,
  beforeEach,
  afterEach,
  jest,
} from "@jest/globals";
import {
  IndexedDBStorage,
  SAVED_GAMES_META_STORE,
  SAVED_GAMES_PAYLOAD_STORE,
  type StorageConfig,
  type StoredGame,
  type StoredGameMeta,
  type StoredGamePayload,
} from "../indexeddb-storage";

const DB_NAME = "TestPlanarNexusMigrationV3";

/**
 * The exact v2 store list, in the exact order the production code used
 * pre-#1572. Keep this in lockstep with the schema audit at the top of
 * indexeddb-storage.ts so the test exercises the real upgrade path.
 */
const V2_FIXTURE_STORES = [
  "decks",
  "saved-games",
  "preferences",
  "usage-tracking",
  "achievements",
  "game-history",
] as const;

const V3_CONFIG: StorageConfig = {
  dbName: DB_NAME,
  version: 3,
  stores: [
    "decks",
    "saved-games",
    SAVED_GAMES_META_STORE,
    SAVED_GAMES_PAYLOAD_STORE,
    "preferences",
    "usage-tracking",
    "achievements",
    "game-history",
  ],
};

/**
 * Open the database at version 2 with a hand-written schema and seed
 * it with a representative record fixture (focused on the rows the
 * split migration must move). Returns once seeding is durable.
 */
async function seedV2Fixture(): Promise<void> {
  const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
    .indexedDB;

  await new Promise<void>((resolve, reject) => {
    const req = idb.open(DB_NAME, 2);
    req.onupgradeneeded = () => {
      const db = req.result;
      // v2 layout — mirrors what the production code lazily creates
      // when it first opens at v2. Do NOT add v3-only fields here.
      const decks = db.createObjectStore("decks", { keyPath: "id" });
      decks.createIndex("name", "name", { unique: false });
      decks.createIndex("format", "format", { unique: false });
      decks.createIndex("createdAt", "createdAt", { unique: false });
      decks.createIndex("updatedAt", "updatedAt", { unique: false });

      const games = db.createObjectStore("saved-games", { keyPath: "id" });
      games.createIndex("name", "name", { unique: false });
      games.createIndex("format", "format", { unique: false });
      games.createIndex("status", "status", { unique: false });
      games.createIndex("savedAt", "savedAt", { unique: false });
      games.createIndex("isAutoSave", "isAutoSave", { unique: false });

      db.createObjectStore("preferences", { keyPath: "id" });

      const usage = db.createObjectStore("usage-tracking", { keyPath: "id" });
      usage.createIndex("provider", "provider", { unique: false });
      usage.createIndex("timestamp", "timestamp", { unique: false });

      db.createObjectStore("achievements", { keyPath: "id" });

      const history = db.createObjectStore("game-history", { keyPath: "id" });
      history.createIndex("date", "date", { unique: false });
      history.createIndex("result", "result", { unique: false });
      history.createIndex("mode", "mode", { unique: false });
    };
    req.onsuccess = () => {
      const db = req.result;
      const tx = db.transaction([...V2_FIXTURE_STORES], "readwrite");
      const stores = {
        decks: tx.objectStore("decks"),
        "saved-games": tx.objectStore("saved-games"),
        preferences: tx.objectStore("preferences"),
        "usage-tracking": tx.objectStore("usage-tracking"),
        achievements: tx.objectStore("achievements"),
        "game-history": tx.objectStore("game-history"),
      };

      // 10 monolithic saved-game rows — the v2 → v3 split MUST move
      // every one of these into the new meta + payload stores without
      // losing payload bytes. Mix of with-replay and no-replay so
      // hasReplay gets exercised in both directions.
      const fixtureRows: StoredGame[] = [];
      for (let i = 0; i < 10; i++) {
        const hasReplay = i % 2 === 0;
        const row: StoredGame = {
          id: `game-${i}`,
          name: `Game ${i}`,
          format: i % 2 === 0 ? "commander" : "standard",
          playerNames: i % 2 === 0 ? ["Alice", "Bob"] : ["Charlie", "Dave"],
          savedAt: 1_700_000_000_000 + i * 1000,
          createdAt: 1_700_000_000_000 + i * 1000 - 60_000,
          turnNumber: i + 1,
          currentPhase: i % 2 === 0 ? "main" : "combat",
          status: i % 3 === 0 ? "completed" : "in_progress",
          isAutoSave: i % 4 === 0,
          autoSaveSlot: i % 4 === 0 ? i % 3 : undefined,
          gameStateJson: `{"compressed":true,"payloadKb":${10 + i},"idx":${i}}`,
          replayJson: hasReplay
            ? `{"replay":true,"actions":${i * 50},"idx":${i}}`
            : undefined,
          metadata: {},
        };
        fixtureRows.push(row);
        stores["saved-games"].put(row);
      }
      void fixtureRows;

      tx.oncomplete = () => {
        db.close();
        resolve();
      };
      tx.onerror = () => reject(tx.error ?? new Error("seed tx failed"));
      tx.onabort = () => reject(tx.error ?? new Error("seed tx aborted"));
    };
    req.onerror = () => reject(req.error ?? new Error("v2 open failed"));
  });
}

/**
 * Drop the test database. Tolerates "not found" because some tests
 * may run against a fresh environment.
 */
async function dropDatabase(): Promise<void> {
  const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
    .indexedDB;
  await new Promise<void>((resolve) => {
    const req = idb.deleteDatabase(DB_NAME);
    req.onsuccess = () => resolve();
    req.onerror = () => resolve();
    req.onblocked = () => resolve();
  });
}

beforeEach(async () => {
  await dropDatabase();
});

afterEach(async () => {
  await dropDatabase();
  jest.restoreAllMocks();
});

describe("IndexedDB schema migration (v2 → v3, issue #1572 saved-games split)", () => {
  it("migrates every pre-split saved-games row into meta + payload stores without data loss", async () => {
    // Seed v2 first, then open v3 on top of it.
    await seedV2Fixture();

    const v3Storage = new IndexedDBStorage(V3_CONFIG);
    await v3Storage.initialize();

    // Every original saved-games record must survive the upgrade — once
    // in the meta store (with payload-snapshot fields) and once in the
    // payload store (with the heavy bytes).
    const metas = await v3Storage.getAll<StoredGameMeta>(
      SAVED_GAMES_META_STORE,
    );
    expect(metas).toHaveLength(10);

    const payloads = await v3Storage.getAll<StoredGamePayload>(
      SAVED_GAMES_PAYLOAD_STORE,
    );
    expect(payloads).toHaveLength(10);

    // Spot-check: pick row 7 (odd idx → no replay) and row 8 (even idx →
    // has replay) and confirm both stores agree on the heavy bytes.
    const meta7 = metas.find((m) => m.id === "game-7");
    expect(meta7).toBeDefined();
    expect(meta7?.name).toBe("Game 7");
    expect(meta7?.format).toBe("standard");
    expect(meta7?.turnNumber).toBe(8);
    expect(meta7?.status).toBe("in_progress");
    expect(meta7?.isAutoSave).toBe(false);
    expect(meta7?.hasReplay).toBe(false);
    expect(meta7?.playerNames).toEqual(["Charlie", "Dave"]);

    const payload7 = payloads.find((p) => p.id === "game-7");
    expect(payload7).toBeDefined();
    expect(payload7?.gameStateJson).toBe(
      '{"compressed":true,"payloadKb":17,"idx":7}',
    );
    expect(payload7?.replayJson).toBeUndefined();

    const meta8 = metas.find((m) => m.id === "game-8");
    expect(meta8).toBeDefined();
    expect(meta8?.format).toBe("commander");
    expect(meta8?.status).toBe("in_progress");
    expect(meta8?.hasReplay).toBe(true);

    const payload8 = payloads.find((p) => p.id === "game-8");
    expect(payload8?.replayJson).toBe(
      '{"replay":true,"actions":400,"idx":8}',
    );

    // isAutoSave=true rows must carry the autoSaveSlot on the meta row.
    const meta0 = metas.find((m) => m.id === "game-0");
    expect(meta0?.isAutoSave).toBe(true);
    expect(meta0?.autoSaveSlot).toBe(0);

    // Legacy saved-games store is left in the schema but the rows are
    // emptied so the v3 build owns the truth. A re-export from v3 will
    // rehydrate from meta + payload (see exportBackup test below).
    const legacy = await v3Storage.getAll<StoredGame>("saved-games");
    expect(legacy).toHaveLength(0);

    await v3Storage.close();
  });

  it("creates every v3 object store from a clean-slate v3 open", async () => {
    // No fixture seeded — database must not exist.
    const storage = new IndexedDBStorage(V3_CONFIG);
    await storage.initialize();

    const idb: IDBFactory = (globalThis as unknown as { indexedDB: IDBFactory })
      .indexedDB;
    const db = await new Promise<IDBDatabase>((resolve, reject) => {
      const req = idb.open(DB_NAME, 3);
      req.onsuccess = () => resolve(req.result);
      req.onerror = () => reject(req.error ?? new Error("v3 open failed"));
    });

    try {
      // Must contain EVERY v3 store, including the legacy one (downgrade
      // safety) AND the new split pair.
      const expectedStores = new Set<string>(V3_CONFIG.stores);
      for (const name of db.objectStoreNames) {
        expect(expectedStores.has(name)).toBe(true);
      }
      expect(db.objectStoreNames.length).toBe(V3_CONFIG.stores.length);

      // Indexes on the new meta store must mirror the legacy store.
      const tx = db.transaction(SAVED_GAMES_META_STORE, "readonly");
      const metaIndexNames = Array.from(tx.objectStore(SAVED_GAMES_META_STORE).indexNames).sort();
      expect(metaIndexNames).toEqual(
        ["format", "isAutoSave", "name", "savedAt", "status"],
      );
    } finally {
      db.close();
      await storage.close();
    }
  });

  it("re-running the migration (close + reopen at v3) is idempotent", async () => {
    await seedV2Fixture();

    // First open: do the v2 → v3 split.
    const first = new IndexedDBStorage(V3_CONFIG);
    await first.initialize();
    await first.close();

    // Second open: re-running the migration must NOT duplicate meta or
    // payload rows, and must NOT re-populate the legacy saved-games store.
    const second = new IndexedDBStorage(V3_CONFIG);
    await second.initialize();

    const metas = await second.getAll<StoredGameMeta>(
      SAVED_GAMES_META_STORE,
    );
    expect(metas).toHaveLength(10);

    const payloads = await second.getAll<StoredGamePayload>(
      SAVED_GAMES_PAYLOAD_STORE,
    );
    expect(payloads).toHaveLength(10);

    const legacy = await second.getAll<StoredGame>("saved-games");
    expect(legacy).toHaveLength(0);

    await second.close();
  });

  it("exportBackup rehydrates meta + payload back into the monolithic StoredGame[] envelope shape", async () => {
    await seedV2Fixture();

    const storage = new IndexedDBStorage(V3_CONFIG);
    await storage.initialize();

    const backup = await storage.exportBackup();

    // The backup envelope still uses the pre-#1572 savedGames field
    // shape (issue acceptance criterion: existing restore paths must
    // continue to round-trip byte-identically). Every original row
    // must appear in the envelope with its payload bytes intact.
    expect(backup.savedGames).toHaveLength(10);
    const game8 = backup.savedGames.find((g) => g.id === "game-8");
    expect(game8?.gameStateJson).toBe(
      '{"compressed":true,"payloadKb":18,"idx":8}',
    );
    expect(game8?.replayJson).toBe(
      '{"replay":true,"actions":400,"idx":8}',
    );
    const game7 = backup.savedGames.find((g) => g.id === "game-7");
    expect(game7?.replayJson).toBeUndefined();

    // Round-trip: clear, then importBackup should restore via the v3
    // split path (writeStoredGameToV3) so the post-import state matches
    // the pre-export state modulo the legacy row cleanup.
    await storage.clear(SAVED_GAMES_META_STORE);
    await storage.clear(SAVED_GAMES_PAYLOAD_STORE);
    await storage.importBackup(backup);

    const metasAfter = await storage.getAll<StoredGameMeta>(
      SAVED_GAMES_META_STORE,
    );
    expect(metasAfter).toHaveLength(10);
    const payloadsAfter = await storage.getAll<StoredGamePayload>(
      SAVED_GAMES_PAYLOAD_STORE,
    );
    expect(payloadsAfter).toHaveLength(10);
    const payload8 = payloadsAfter.find((p) => p.id === "game-8");
    expect(payload8?.replayJson).toBe(
      '{"replay":true,"actions":400,"idx":8}',
    );

    await storage.close();
  });
});